import {
  BaseSource,
  DdcGatherItems,
} from "https://deno.land/x/ddc_vim@v5.0.1/types.ts#^";
import { GatherArguments } from "https://deno.land/x/ddc_vim@v5.0.1/base/source.ts#^";

type Params = Record<string, never>;

export class Source extends BaseSource<Params> {
  async gather(args: GatherArguments<Params>): Promise<DdcGatherItems> {
    if (
      !args.context.input.match(
        /\\(?:ifbeamercolorempty(?:\[[bf]g\])?|setbeamercolor\*?|usebeamercolor\*?(?:\[[bf]g\])?)\{\w*$/,
      )
    ) {
      return [];
    }

    return await Promise.all([
      "abstract title",
      "abstract",
      "alerted text",
      "author in head/foot",
      "author in sidebar",
      "author",
      "background canvas",
      "background",
      "bibliography entry author",
      "bibliography entry location",
      "bibliography entry note",
      "bibliography entry title",
      "bibliography item",
      "block body alerted",
      "block body example",
      "block body",
      "block title alerted",
      "block title example",
      "block title",
      "button border",
      "button",
      "caption name",
      "caption",
      "date in head/foot",
      "date in sidebar",
      "date",
      "description body",
      "description item",
      "enumerate item",
      "enumerate subitem",
      "enumerate subsubitem",
      "example text",
      "fine separation line",
      "footline",
      "framesubtitle",
      "frametitle right",
      "frametitle",
      "headline",
      "institute in head/foot",
      "institute in sidebar",
      "institute",
      "item projected",
      "item",
      "itemize item",
      "itemize subitem",
      "itemize subsubitem",
      "itemize/enumerate body",
      "itemize/enumerate subbody",
      "itemize/enumerate subsubbody",
      "local structure",
      "logo",
      "lower separation line foot",
      "lower separation line head",
      "math text displayed",
      "math text inlined",
      "math text",
      "middle separation line foot",
      "middle separation line head",
      "mini frame",
      "navigation symbols dimmed",
      "navigation symbols",
      "normal text in math text",
      "normal text",
      "note date",
      "note page",
      "note title",
      "page number in head/foot",
      "palette primary",
      "palette quaternary",
      "palette secondary",
      "palette sidebar primary",
      "palette sidebar quaternary",
      "palette sidebar secondary",
      "palette sidebar tertiary",
      "palette tertiary",
      "part name",
      "part title",
      "qed symbol",
      "quotation",
      "quote",
      "section in head/foot",
      "section in sidebar shaded",
      "section in sidebar",
      "section in toc shaded",
      "section in toc",
      "section name",
      "section number projected",
      "section title",
      "separation line",
      "sidebar #1",
      "sidebar left",
      "sidebar right",
      "sidebar",
      "structure",
      "subitem projected",
      "subitem",
      "subsection in head/foot",
      "subsection in sidebar shaded",
      "subsection in sidebar",
      "subsection in toc shaded",
      "subsection in toc",
      "subsection name",
      "subsection number projected",
      "subsection title",
      "subsubitem projected",
      "subsubitem",
      "subsubsection in head/foot",
      "subsubsection in sidebar shaded",
      "subsubsection in sidebar",
      "subsubsection in toc shaded",
      "subsubsection in toc",
      "subsubsection number projected",
      "subtitle",
      "title in head/foot",
      "title in sidebar",
      "title",
      "titlegraphic",
      "titlelike",
      "upper separation line foot",
      "upper separation line head",
      "verse",
    ].map(
      (word) => Promise.resolve({ menu: "beamercolor", word: word }),
    ));
  }

  params(): Params {
    return {};
  }
}
