# vi: fdm=marker fmr=[,]
import re
from deoplete.base.source import Base


class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)
        self.name = "tex.command"
        self.mark = "[cmd]"
        self.filetypes = ["tex"]
        self.input_pattern = r"\\[A-Za-z]*$"
        self.rank = 1000
        pkgcmds = {
            "": [
                "abovecaptionskip",
                "abovedisplayshortskip",
                "abovedisplayskip",
                "addtocounter",
                "addtolength",
                "aftergroup",
                "Alph",
                "alph",
                "alpha",
                "approx",
                "arabic",
                "arccos",
                "arcsin",
                "arctan",
                "arg",
                "AtBeginDocument",
                "AtEndDocument",
                "AtEndOfClass",
                "AtEndOfPackage",
                "author",
                "baselineskip",
                "baselinestretch",
                "belowdisplayshortskip",
                "belowdisplayskip",
                "beta",
                "bfseries",
                "bigbreak",
                "bigcap",
                "bigcup",
                "bigodot",
                "bigoplus",
                "bigotimes",
                "bigskip",
                "bigsqcup",
                "bigtriangledown",
                "bigtriangleup",
                "biguplus",
                "bigvee",
                "bigwedge",
                "bmod",
                "bot",
                "bowtie",
                "breve",
                "bullet",
                "cap",
                "cdot",
                "cdotp",
                "cdots",
                "centering",
                "CheckCommand",
                "chi",
                "ClassError",
                "ClassInfo",
                "ClassWarning",
                "ClassWarningNoLine",
                "clearpage",
                "cos",
                "cosh",
                "cot",
                "coth",
                "csc",
                "csname",
                "CurrentOption",
                "dagger",
                "ddagger",
                "DeclareOption",
                "DeclareRobustCommand",
                "deg",
                "Delta",
                "delta",
                "det",
                "dim",
                "displaymath",
                "displaystyle",
                "documentclass",
                "Downarrow",
                "else",
                "emptyset",
                "endcsname",
                "endinput",
                "enskip",
                "enspace",
                "ensuremath",
                "epsilon",
                "equiv",
                "eta",
                "everymath",
                "ExecuteOptions",
                "exists",
                "exp",
                "fbox",
                "fboxrule",
                "fboxsep",
                "fi",
                "fill",
                "floatsep",
                "footnotesize",
                "forall",
                "framebox",
                "Gamma",
                "gamma",
                "gcd",
                "geq",
                "gg",
                "hbar",
                "hfill",
                "hline",
                "hom",
                "hphantom",
                "hrule",
                "hrulefill",
                "hspace",
                "if",
                "iffalse",
                "IfFileExists",
                "ifhmode",
                "in",
                "inf",
                "infty",
                "input",
                "intextsep",
                "iota",
                "itemindent",
                "itemsep",
                "itshape",
                "jobname",
                "kappa",
                "ker",
                "label",
                "labelsep",
                "Lambda",
                "lambda",
                "lceil",
                "leavevmode",
                "Leftarrow",
                "leftarrow",
                "leftharpoondown",
                "leftharpoonup",
                "Leftrightarrow",
                "leftrightarrow",
                "leq",
                "let",
                "lfloor",
                "lg",
                "lim",
                "liminf",
                "limsup",
                "lineskip",
                "linewidth",
                "listfiles",
                "ll",
                "llap",
                "ln",
                "LoadClass",
                "LoadClassWithOptions",
                "log",
                "Longleftarrow",
                "Longleftrightarrow",
                "Longrightarrow",
                "makeatletter",
                "makeatother",
                "makebox",
                "mathbb",
                "mathbin",
                "mathclose",
                "mathopen",
                "mathord",
                "mathrel",
                "mathstrut",
                "mathsurround",
                "max",
                "mbox",
                "mdseries",
                "medbreak",
                "medmuskip",
                "medskip",
                "medspace",
                "mid",
                "min",
                "mp",
                "mu",
                "muskip",
                "nabla",
                "nearrow",
                "NeedsTeXFormat",
                "neg",
                "negmedspace",
                "negthickspace",
                "negthinspace",
                "newcommand",
                "newenvironment",
                "newlength",
                "newline",
                "newpage",
                "ni",
                "nobreak",
                "nobreakdashes",
                "nobreakspace",
                "noindent",
                "nopagebreak",
                "normalbaselines",
                "normalbaselineskip",
                "normalfont",
                "normallineskip",
                "normalsize",
                "nu",
                "nwarrow",
                "odot",
                "oldstylenums",
                "Omega",
                "omega",
                "ominus",
                "onecolumn",
                "oplus",
                "OptionNotUsed",
                "oslash",
                "otimes",
                "overfullrule",
                "PackageError",
                "PackageInfo",
                "PackageWarning",
                "PackageWarningNoLine",
                "pagebreak",
                "pagenumbering",
                "pageref",
                "paperheight",
                "paperwidth",
                "par",
                "parallel",
                "parbox",
                "parfillskip",
                "parindent",
                "parskip",
                "partial",
                "PassOptionsToClass",
                "PassOptionsToPackage",
                "perp",
                "phantom",
                "Phi",
                "phi",
                "Pi",
                "pi",
                "pm",
                "pmod",
                "Pr",
                "prime",
                "ProcessOptions",
                "prod",
                "propto",
                "providecommand",
                "ProvidesClass",
                "ProvidesFile",
                "ProvidesPackage",
                "ProvideTextCommand",
                "ProvideTextCommandDefault",
                "Psi",
                "psi",
                "qquad",
                "quad",
                "raisebox",
                "rceil",
                "ref",
                "relax",
                "renewcommand",
                "renewenvironment",
                "RequirePackage",
                "RequirePackageWithOptions",
                "rfloor",
                "rho",
                "right",
                "Rightarrow",
                "rightarrow",
                "rightharpoondown",
                "rightharpoonup",
                "rlap",
                "rmfamily",
                "Roman",
                "roman",
                "savebox",
                "scriptscriptstyle",
                "scriptsize",
                "scriptstyle",
                "scshape",
                "searrow",
                "sec",
                "setcounter",
                "setlength",
                "setminus",
                "sffamily",
                "show",
                "Sigma",
                "sigma",
                "sim",
                "simeq",
                "sin",
                "sinh",
                "slshape",
                "smallskip",
                "smash",
                "stackrel",
                "stepcounter",
                "subset",
                "subseteq",
                "sum",
                "sup",
                "suppressfloats",
                "supset",
                "supseteq",
                "swarrow",
                "tan",
                "tanh",
                "tau",
                "textasciicircum",
                "textasciitilde",
                "textasteriskcentered",
                "textbackslash",
                "textbf",
                "textbigcircle",
                "textbullet",
                "textcircled",
                "textdagger",
                "textheight",
                "textit",
                "textmd",
                "textnormal",
                "textperiodcentered",
                "textrm",
                "textsc",
                "textsf",
                "textsl",
                "textstyle",
                "textsubscript",
                "textsuperscript",
                "texttt",
                "textup",
                "textvisiblespace",
                "textwidth",
                "the",
                "theequation",
                "thefootnote",
                "thepage",
                "therefore",
                "Theta",
                "theta",
                "thicklines",
                "thickmuskip",
                "thickspace",
                "thinlines",
                "thinmuskip",
                "thinspace",
                "times",
                "title",
                "ttfamily",
                "twocolumn",
                "Uparrow",
                "Updownarrow",
                "upshape",
                "Upsilon",
                "upsilon",
                "usepackage",
                "varDelta",
                "varepsilon",
                "varGamma",
                "varLambda",
                "varOmega",
                "varPhi",
                "varphi",
                "varPi",
                "varPsi",
                "varrho",
                "varSigma",
                "varsigma",
                "vartheta",
                "varXi",
                "Vert",
                "vphantom",
                "vrule",
                "vspace",
                "Xi",
                "xi",
                "Zeta",
                "zeta",
            ],
            "acro": [
                "Ac",
                "Ac*",
                "Acf",
                "Acf*",
                "Acfp",
                "Acfp*",
                "Acl",
                "Acl*",
                "Aclp",
                "Aclp*",
                "Acp",
                "Acp*",
                "AcroRegisterTrailing",
                "Acsingle",
                "DeclareAcroCommand",
                "DeclareAcroExtraStyle",
                "DeclareAcroFirstStyle",
                "DeclareAcroListHeading",
                "DeclareAcroListStyle",
                "DeclareAcroPageStyle",
                "DeclareAcronym",
                "Iac",
                "NewAcroCommand",
                "NewPseudoAcroCommand",
                "ProvideAcroCommand",
                "ProvideAcroEnding",
                "RenewAcroCommand",
                "ac",
                "ac*",
                "aca",
                "aca*",
                "acap",
                "acap*",
                "acbarrier",
                "acdot",
                "acf",
                "acf*",
                "acfirstupper",
                "acflike",
                "acfp",
                "acfp*",
                "acfplike",
                "acg",
                "aciffirst",
                "aciftrailing",
                "acifused",
                "acl",
                "acl*",
                "aclp",
                "aclp*",
                "acp",
                "acp*",
                "acpdfstring",
                "acpdfstringplural",
                "acreset",
                "acresetall",
                "acroenparen",
                "acs",
                "acs*",
                "acsetup",
                "acsingle",
                "acsp",
                "acsp*",
                "acspace",
                "acswitchoff",
                "acswitchon",
                "acuse",
                "acuseall",
                "iac",
                "iacl",
                "iacs",
                "makefirstuc",
                "printacronyms",
            ],
            "adjustbox": [
                "adjustbox",
                "adjustimage",
                "adjincludegraphics",
            ],
            "algorithm2e": [
                "KwIn",
                "LinesNumbered",
                "KwOut",
                "KwData",
                "KwResult",
                "KwTo",
                "KwRet",
                "Return",
                "Begin",
            ],
            "amsmath": [
                "Big",
                "Bigg",
                "DeclareMathOperator",
                "DeclarePairedDelimiter",
                "Longleftarrow",
                "Longleftrightarrow",
                "Longrightarrow",
                "allowdisplaybreaks",
                "bar",
                "big",
                "bigg",
                "binom",
                "boldsymbol",
                "ddot",
                "displaybreak",
                "displaystyle",
                "dot",
                "dots",
                "dotsb",
                "dotsc",
                "dotsm",
                "dotso",
                "genfrac",
                "gtrless",
                "hat",
                "hookleftarrow",
                "hookrightarrow",
                "iff",
                "iiiint",
                "iiint",
                "iint",
                "impliedby",
                "implies",
                "intertext",
                "lVert",
                "lessgtr",
                "longleftarrow",
                "longleftrightarrow",
                "longmapsto",
                "longrightarrow",
                "lvert",
                "mapsto",
                "mspace",
                "nLeftarrow",
                "nLeftrightarrow",
                "nRightarrow",
                "nexists",
                "nonumber",
                "notag",
                "oint",
                "operatorname",
                "operatorname*",
                "rVert",
                "rvert",
                "scriptstyle",
                "substack",
                "tilde",
                "tmspace",
                "varnothing",
            ],
            "article": [
                "abovecaptionskip",
                "appendixname",
                "belowcaptionskip",
                "figurename",
                "maketitle",
                "paragraph",
                "section",
                "subparagraph",
                "subsection",
                "subsubsection",
                "tablename",
                "tableofcontents",
                "thefigure",
                "thepart",
                "thesection",
                "thesubsection",
                "thesubsubsection",
                "thetable",
            ],
            "array": [
                "multicolumn",
                "newcolomntype",
            ],
            "beamer": [
                "AtBeginDocument",
                "AtBeginLecture",
                "AtBeginNote",
                "AtBeginPart",
                "AtBeginSection",
                "AtBeginSubsection",
                "AtBeginSubsubsection",
                "AtEndNote",
                "addtobeamertemplate",
                "alt",
                "defbeamertemplate",
                "hypertarget",
                "insertappendixendpage",
                "insertappendixframenumber",
                "insertappendixstartpage",
                "insertauthor",
                "insertbackfindforwardnavigationsymbol",
                "insertbiblabel",
                "insertblocktitle",
                "insertbuttontext",
                "insertcaption",
                "insertcaptionname",
                "insertcaptionnumber",
                "insertcontinuationcount",
                "insertcontinuationcountroman",
                "insertcontinuationtext",
                "insertdate",
                "insertdescriptionitem",
                "insertdocnavigationsymbol",
                "insertdocumentendpage",
                "insertdocumentstartpage",
                "insertenumlabel",
                "insertfootnotemark",
                "insertfootnotetext",
                "insertframeendpage",
                "insertframenavigationsymbol",
                "insertframenumber",
                "insertframestartpage",
                "insertframesubtitle",
                "insertframetitle",
                "insertgotosymbol",
                "insertinstitute",
                "insertlogo",
                "insertmainframenumber",
                "insertnavigation",
                "insertnote",
                "insertoverlaynumber",
                "insertpagenumber",
                "insertpart",
                "insertpartendpage",
                "insertpartheadnumber",
                "insertpartnumber",
                "insertpartstartpage",
                "insertpresentationendpage",
                "insertpresentationstartpage",
                "insertreturnsymbol",
                "insertromanpartnumber",
                "insertsection",
                "insertsectionendpage",
                "insertsectionhead",
                "insertsectionheadnumber",
                "insertsectionnavigation",
                "insertsectionnavigationhorizontal",
                "insertsectionnavigationsymbol",
                "insertsectionnumber",
                "insertsectionstartpage",
                "insertshortauthor",
                "insertshortdate",
                "insertshortinstitute",
                "insertshortpart",
                "insertshortsubtitle",
                "insertshorttitle",
                "insertskipsymbol",
                "insertslideintonotes",
                "insertslidenavigationsymbol",
                "insertslidenumber",
                "insertsubenumlabel",
                "insertsubsection",
                "insertsubsectionendpage",
                "insertsubsectionhead",
                "insertsubsectionheadnumber",
                "insertsubsectionnavigation",
                "insertsubsectionnavigationhorizontal",
                "insertsubsectionnavigationsymbol",
                "insertsubsectionnumber",
                "insertsubsectionstartpage",
                "insertsubsubenumlabel",
                "insertsubsubsection",
                "insertsubsubsectionhead",
                "insertsubsubsectionheadnumber",
                "insertsubtitle",
                "inserttheoremaddition",
                "inserttheoremblockenv",
                "inserttheoremheadfont",
                "inserttheoremname",
                "inserttheoremnumber",
                "inserttheorempunctuation",
                "inserttitle",
                "inserttitlegraphic",
                "inserttocsection",
                "inserttocsectionnumber",
                "inserttocsubsection",
                "inserttocsubsectionnumber",
                "inserttocsubsubsection",
                "inserttocsubsubsectionnumber",
                "inserttotalframenumber",
                "insertverticalnavigation",
                "invisible",
                "only",
                "onslide",
                "setbeamercolor",
                "setbeamerfont",
                "setbeamersize",
                "setbeamertemplate",
                "temporal",
                "uncover",
                "usebackgroundtemplate",
                "usebeamercolor",
                "usebeamerfont",
                "usebeamertemplate",
                "usecolortheme",
                "usefonttheme",
                "useinnertheme",
                "useoutertheme",
                "usetheme",
                "visible",
            ],
            "biblatex": [
                "AtBeginBibliography",
                "AtBeginBiblist",
                "AtDataInput",
                "AtEachCitekey",
                "AtEveryBibitem",
                "AtEveryBiblistitem",
                "AtEveryCite",
                "AtEveryCitekey",
                "AtEveryMultiCite",
                "Autocite",
                "Autocite*",
                "Cite",
                "Citeauthor",
                "Citeauthor*",
                "Parencite",
                "Textcite",
                "addbibresource",
                "addglobalbib",
                "autocite",
                "autocite",
                "autocite*",
                "bibbysection",
                "bibbysegment",
                "brackettext",
                "cite",
                "cite*",
                "citeauthor",
                "citeauthor*",
                "citedate",
                "citedate*",
                "citetitle",
                "citetitle*",
                "citeurl",
                "citeyear",
                "citeyear*",
                "clearfield",
                "endrefsection",
                "footfullcite",
                "fullcite",
                "newrefsection",
                "newrefsegment",
                "nocite",
                "parencite",
                "parencite",
                "parencite*",
                "parentext",
                "printbibliography",
                "supercite",
                "textcite",
            ],
            "booktabs": [
                "addlinespace",
                "bottomrule",
                "cmidrule",
                "midrule",
                "morecmidrule",
                "specialrule",
                "toprule",
            ],
            "chemfig": [
                "Chemabove",
                "Chembelow",
                "arrow",
                "chemabove",
                "chembelow",
                "chemdown",
                "chemfig",
                "chemleft",
                "chemmove",
                "chemname",
                "chemnameinit",
                "chemright",
                "chemskipalign",
                "chemup",
                "definearrow",
                "definesubmol",
                "hflipnext",
                "polymerdelim",
                "printatom",
                "redefinesubmol",
                "resetchemfig",
                "schemestart",
                "schemestop",
                "setchemfig",
                "subscheme",
                "vflipnext",
            ],
            "dirtree": [
                "DTAtCode",
                "DTbaselineskip",
                "DTcomment",
                "DTsetlength",
                "DTstyle",
                "DTstylecomment",
            ],
            "expl3": [
                "ExplSyntaxOff",
                "ExplSyntaxOn",
                "GetIdInfo",
                "ProvideExplClass",
                "ProvideExplFile",
                "ProvideExplPackage",
            ],
            "fontawesome5": [
                "faIcon",
            ],
            "fontspec": [
                "addfontfeature",
                "defaultfontfeatures",
                "defaultfontfeatures+",
                "fontspec",
                "newfontface",
                "newfontfamily",
                "renewfontfamily",
                "setfontfamily",
                "setmainfont",
                "setmonofont",
                "setsansfont",
            ],
            "graphicx": [
                "includegraphics",
                "resizebox",
                "scalebox",
            ],
            "hyperref": [
                "autopageref",
                "autoref",
                "belowpdfbookmark",
                "currentpdfbookmark",
                "href",
                "hyperimage",
                "hyperlink",
                "hyperpage",
                "hypersetup",
                "hypertarget",
                "nolinkurl",
                "pageref",
                "pdfbookmark",
                "phantomsection",
                "subpdfbookmark",
                "texorpdfstring",
                "thispdfpagelabel",
                "url",
                # "IfHyperBoolean",
                # "IfHyperBooleanExists",
                # "hyperbaseurl",
                # "hypercalcbp",
                # "hyperdef",
                # "hyperref",
                # "pdfstringdef",
            ],
            "jlreq": [
                "DeclareBlockHeading",
                "DeclareTobiraHeading",
                "ModifyHeading",
                "NewBlockHeading",
                "NewTobiraHeading",
                "ProvideBlockHeading",
                "ProvideTobiraHeading",
                "RenewBlockHeading",
                "RenewTobiraHeading",
                "SaveHeading",
                "SetBlockHeadingSpaces",
                "jlreqsetup",
                "newblock",
            ],
            "KOMA-Script": [
                "CloneTOCEntryStyle",
                "RedeclareSectionCommand",
                "TOCEntryStyleInitCode",
                "TOCEntryStyleStartInitCode",
                "abstractname",
                "addchap",
                "addchap*",
                "addchapmark",
                "addchaptertocentry",
                "addcontentsline",
                "addpart",
                "addpart*",
                "addparttocentry",
                "addsec",
                "addsec*",
                "addsectiontocentry",
                "addtokomafont",
                "appendix",
                "appendixname",
                "backmatter",
                "caption",
                "cehead",
                "chapter",
                "chapter*",
                "chapterformat",
                "chaptername",
                "chead",
                "cohead",
                "figurename",
                "frontmatter",
                "ihead",
                "lehead",
                "lohead",
                "newcaptionname*",
                "newkomafont",
                "ohead",
                "othersectionlevelsformat",
                "paragraphformat",
                "part",
                "part*",
                "partformat",
                "partname",
                "rehead",
                "rohead",
                "section",
                "section*",
                "sectionformat",
                "setcapindent",
                "setkomafont",
                "subparagraphformat",
                "subsection",
                "subsection*",
                "subsectionformat",
                "subsubsection",
                "subsubsection*",
                "subsubsectionformat",
                "subtitle",
                "tablename",
                "title",
            ],
            "mathtools": [
                "DeclarePairedDelimiter",
                "DeclarePairedDelimiterX",
                "adjustlimits",
                "overbrace",
                "shortintertext",
                "underbrace",
                # "Aboxed",
                # "ArrowBetweenLines",
                # "ArrowBetweenLines*",
                # "Colonapprox",
                # "Coloneq",
                # "Coloneqq",
                # "Colonsim",
                # "DeclareMathSizes",
                # "DeclarePairedDelimiterXPP",
                # "Eqcolon",
                # "Eqqcolon",
                # "LaTeXoverbrace",
                # "LaTeXunderbrace",
                # "MTFlushSpaceAbove",
                # "MTFlushSpaceBelow",
                # "MoveEqLeft",
                # "SwapAboveDisplaySkip",
                # "bigtimes",
                # "clap",
                # "colonapprox",
                # "coloneq",
                # "coloneqq",
                # "colonsim",
                # "cramped",
                # "crampedllap",
                # "crampedrlap",
                # "dblcolon",
                # "eqcolon",
                # "eqqcolon",
                # "lparen",
                # "mathclap",
                # "mathllap",
                # "mathmakebox",
                # "mathmbox",
                # "mathrlap",
                # "ndownarrow",
                # "newgathered",
                # "newtagform",
                # "norefeq",
                # "nuparrow",
                # "ordinarycolon",
                # "overbracket",
                # "prescript",
                # "reDeclarePairedDelimiterInnerWrapper",
                # "refeq",
                # "renewgathered",
                # "renewtagform",
                # "rparen",
                # "shortvdotswithin",
                # "shortvdotswithin*",
                # "smashoperator",
                # "splitfrac",
                # "underbracket",
                # "usetagform",
                # "vcentcolon",
                # "vdotswithin",
                # "xLeftarrow",
                # "xLeftrightarrow",
                # "xRightarrow",
                # "xhookleftarrow",
                # "xhookrightarrow",
                # "xleftharpoondown",
                # "xleftharpoonup",
                # "xleftrightarrow",
                # "xleftrightharpoons",
                # "xmapsto",
                # "xrightharpoondown",
                # "xrightharpoonup",
                # "xrightleftharpoons",
            ],
            "mleftright": [
                "mleft",
                "mright",
                "mleftrightrestore",
                "mleftright",
            ],
            "minted": [
                "inputminted",
                "listingscaption",
                "listoflistingscaption",
                "newminted",
                "mint",
                "mintinline",
                "usemintedstyle",
            ],
            "pdfpages": [
                "includepdf",
            ],
            "pgffor": [
                "foreach",
            ],
            "pgfmath": [
                "pgfmathaddtocount",
                "pgfmathaddtocounter",
                "pgfmathaddtolength",
                "pgfmathdeclarefunction",
                "pgfmathparse",
                "pgfmathredeclarefunction",
                "pgfmathresult",
                "pgfmathsetcount",
                "pgfmathsetcounter",
                "pgfmathsetlength",
                # "pgfmathHex",
                # "pgfmathMod",
                # "pgfmathabs",
                # "pgfmathacos",
                # "pgfmathadd",
                # "pgfmathand",
                # "pgfmathanglebetweenlines",
                # "pgfmathanglebetweenpoints",
                # "pgfmathapproxequalto",
                # "pgfmatharray",
                # "pgfmathasin",
                # "pgfmathatantwo",
                # "pgfmathbasetoBase",
                # "pgfmathbasetobase",
                # "pgfmathbasetodec",
                # "pgfmathbin",
                # "pgfmathceil",
                # "pgfmathcos",
                # "pgfmathcosec",
                # "pgfmathcosh",
                # "pgfmathcot",
                # "pgfmathdeclarerandomlist",
                # "pgfmathdectoBase",
                # "pgfmathdectobase",
                # "pgfmathdeg",
                # "pgfmathdepth",
                # "pgfmathdiv",
                # "pgfmathdivide",
                # "pgfmathe",
                # "pgfmathequal",
                # "pgfmathexp",
                # "pgfmathfactorial",
                # "pgfmathfalse",
                # "pgfmathfloat",
                # "pgfmathfloatabserror",
                # "pgfmathfloatcreate",
                # "pgfmathfloatgetexponent",
                # "pgfmathfloatgetflags",
                # "pgfmathfloatgetflagstomacro",
                # "pgfmathfloatgetmantissa",
                # "pgfmathfloatgetmantissatok",
                # "pgfmathfloatifapproxequalrel",
                # "pgfmathfloatifflags",
                # "pgfmathfloatint",
                # "pgfmathfloatlessthan",
                # "pgfmathfloatmultiplyfixed",
                # "pgfmathfloatparsenumber",
                # "pgfmathfloatqparsenumber",
                # "pgfmathfloatrelerror",
                # "pgfmathfloatround",
                # "pgfmathfloatroundzerofill",
                # "pgfmathfloatsetextprecision",
                # "pgfmathfloatshift",
                # "pgfmathfloattoextentedprecision",
                # "pgfmathfloattofixed",
                # "pgfmathfloattoint",
                # "pgfmathfloattomacro",
                # "pgfmathfloattoregisters",
                # "pgfmathfloattoregisterstok",
                # "pgfmathfloattosci",
                # "pgfmathfloatvalueof",
                # "pgfmathfloor",
                # "pgfmathfrac",
                # "pgfmathgcd",
                # "pgfmathgeneratepseudorandomnumber",
                # "pgfmathgreater",
                # "pgfmathheight",
                # "pgfmathhex",
                # "pgfmathifisint",
                # "pgfmathifthenelse",
                # "pgfmathint",
                # "pgfmathiseven",
                # "pgfmathisodd",
                # "pgfmathisprime",
                # "pgfmathless",
                # "pgfmathln",
                # "pgfmathlog",
                # "pgfmathlogten",
                # "pgfmathlogtwo",
                # "pgfmathmax",
                # "pgfmathmin",
                # "pgfmathmod",
                # "pgfmathmultiply",
                # "pgfmathneg",
                # "pgfmathnot",
                # "pgfmathnotequal",
                # "pgfmathnotgreater",
                # "pgfmathnotless",
                # "pgfmathoct",
                # "pgfmathor",
                # "pgfmathpi",
                # "pgfmathpostparse",
                # "pgfmathpow",
                # "pgfmathprintnumber",
                # "pgfmathprintnumberto",
                # "pgfmathqparse",
                # "pgfmathrad",
                # "pgfmathrand",
                # "pgfmathrandom",
                # "pgfmathrandominteger",
                # "pgfmathrandomitem",
                # "pgfmathreal",
                # "pgfmathreciprocal",
                # "pgfmathrnd",
                # "pgfmathround",
                # "pgfmathroundto",
                # "pgfmathroundtozerofill",
                # "pgfmathscalar",
                # "pgfmathsec",
                # "pgfmathsetbasenumberlength",
                # "pgfmathsetlengthmacro",
                # "pgfmathsetmacro",
                # "pgfmathsetseed",
                # "pgfmathsign",
                # "pgfmathsin",
                # "pgfmathsinh",
                # "pgfmathsqrt",
                # "pgfmathsubtract",
                # "pgfmathtan",
                # "pgfmathtanh",
                # "pgfmathtodigitlist",
                # "pgfmathtrue",
                # "pgfmathtruncatemacro",
                # "pgfmathveclen",
                # "pgfmathwidth",
            ],
            "physics": [
                "Bqty",
                "PV",
                "Res",
                "Tr",
                "Trace",
                "abs",
                "abs*",
                "absolutevalue",
                "absolutevalue*",
                "acomm",
                "anticommutator",
                "bqty",
                "bra",
                "bra*",
                "braket",
                "braket*",
                "comm",
                "comm*",
                "commutator",
                "commutator*",
                "dd",
                "derivative",
                "derivative*",
                "differential",
                "dv",
                "dv*",
                "dyad",
                "dyad*",
                "erf",
                "ev",
                "ev*",
                "ev**",
                "eval",
                "eval*",
                "evaluated",
                "evaluated*",
                "expectationvalue",
                "expectationvalue*",
                "expectationvalue**",
                "expval",
                "expval*",
                "expval**",
                "fdv",
                "fdv*",
                "functionalderivative",
                "functionalderivative*",
                "innerproduct",
                "innerproduct*",
                "ip",
                "ip*",
                "ket",
                "ket*",
                "ketbra",
                "ketbra*",
                "matrixel",
                "matrixel*",
                "matrixel**",
                "matrixelement",
                "matrixelement*",
                "matrixelement**",
                "mel",
                "mel*",
                "mel**",
                "norm",
                "norm*",
                "op",
                "op*",
                "order",
                "order*",
                "outerproduct",
                "outerproduct*",
                "partialderivative",
                "partialderivative*",
                "pb",
                "pderivative",
                "pderivative*",
                "poissonbracket",
                "pqty",
                "principalvalue",
                "pv",
                "qty",
                "quantity",
                "rank",
                "tr",
                "trace",
                "var",
                "variation",
                "vqty",
            ],
            "ragged2e": [
                "Centering",
                "RaggedLeft",
                "RaggedRight",
                "justifying",
            ],
            "siunitx": [
                "DeclareSIQualifier",
                "DeclareSIUnit",
                "SI",
                "ang",
                "num",
                "si",
                "sisetup",
                "tablenum",
            ],
            "subfiles": [
                "subfile",
            ],
            "tikz": [
                "clip",
                "coordinate",
                "draw",
                "fill",
                "filldraw",
                "node",
                "nodepart",
                "path",
                "pattern",
                "shade",
                "shadedraw",
                "tikz",
                "tikzset",
                "useasboundingbox",
                "usetikzlibrary",
            ],
            "tikz/external": [
                "image",
                "pgfactualjobname",
                "texsource",
                "tikzappendtofigurename",
                "tikzexternaldisable",
                "tikzexternalenable",
                "tikzexternalfiledependsonfile",
                "tikzexternalize",
                "tikzexternalrealjob",
                "tikzifexternalizing",
                "tikzifexternalizingnext",
                "tikzpicturedependsonfile",
                "tikzsetexternalprefix",
                "tikzsetfigurename",
                "tikzsetnextfilename",
            ],
            "tikz/multipart": [
                "nodepart",
            ],
            "tocstyle": [
                "aliastoc",
                "deactivatetocstyle",
                "iftochaschapter",
                "iftochasdepth",
                "newtocstyle",
                "numberline",
                "reactivatetocstyle",
                "selecttocstyleoption",
                "settocfeature",
                "settocstylefeature",
                "showtoc",
                "tocbreakscareless",
                "tocbreaksstrict",
                "tocflat",
                "tocfullflat",
                "tocgraduated",
                "tocindentauto",
                "tocindentmanual",
                "tocstyleTOC",
                "tocstyledepth",
                "toctextentriesindented",
                "usetocstyle",
            ],
            "typicons": [
                "tiAdjustBrightness",
                "tiAdjustContrast",
                "tiAnchorOutline",
                "tiAnchor",
                "tiArchive",
                "tiArrowBackOutline",
                "tiArrowBack",
                "tiArrowDownOutline",
                "tiArrowDownThick",
                "tiArrowDown",
                "tiArrowForwardOutline",
                "tiArrowForward",
                "tiArrowLeftOutline",
                "tiArrowLeftThick",
                "tiArrowLeft",
                "tiArrowLoopOutline",
                "tiArrowLoop",
                "tiArrowMaximiseOutline",
                "tiArrowMaximise",
                "tiArrowMinimiseOutline",
                "tiArrowMinimise",
                "tiArrowMoveOutline",
                "tiArrowMove",
                "tiArrowRepeatOutline",
                "tiArrowRepeat",
                "tiArrowRightOutline",
                "tiArrowRightThick",
                "tiArrowRight",
                "tiArrowShuffle",
                "tiArrowSortedDown",
                "tiArrowSortedUp",
                "tiArrowSyncOutline",
                "tiArrowSync",
                "tiArrowUnsorted",
                "tiArrowUpOutline",
                "tiArrowUpThick",
                "tiArrowUp",
                "tiAt",
                "tiAttachmentOutline",
                "tiAttachment",
                "tiBackspaceOutline",
                "tiBackspace",
                "tiBatteryCharge",
                "tiBatteryFull",
                "tiBatteryHigh",
                "tiBatteryLow",
                "tiBatteryMid",
                "tiBeaker",
                "tiBeer",
                "tiBell",
                "tiBook",
                "tiBookmark",
                "tiBriefcase",
                "tiBrush",
                "tiBusinessCard",
                "tiCalculator",
                "tiCalendarOutline",
                "tiCalendar",
                "tiCameraOutline",
                "tiCamera",
                "tiCancelOutline",
                "tiCancel",
                "tiChartAreaOutline",
                "tiChartArea",
                "tiChartBarOutline",
                "tiChartBar",
                "tiChartLineOutline",
                "tiChartLine",
                "tiChartPieOutline",
                "tiChartPie",
                "tiChevronLeftOutline",
                "tiChevronLeft",
                "tiChevronRightOutline",
                "tiChevronRight",
                "tiClipboard",
                "tiCloudStorage",
                "tiCloudStorageOutline",
                "tiCodeOutline",
                "tiCode",
                "tiCoffee",
                "tiCogOutline",
                "tiCog",
                "tiCompass",
                "tiContacts",
                "tiCreditCard",
                "tiCss3",
                "tiDatabase",
                "tiDeleteOutline",
                "tiDelete",
                "tiDeviceDesktop",
                "tiDeviceLaptop",
                "tiDevicePhone",
                "tiDeviceTablet",
                "tiDirections",
                "tiDivideOutline",
                "tiDivide",
                "tiDocumentAdd",
                "tiDocumentDelete",
                "tiDocumentText",
                "tiDocument",
                "tiDownloadOutline",
                "tiDownload",
                "tiDropbox",
                "tiEdit",
                "tiEjectOutline",
                "tiEject",
                "tiEqualsOutline",
                "tiEquals",
                "tiExportOutline",
                "tiExport",
                "tiEyeOutline",
                "tiEye",
                "tiFeather",
                "tiFilm",
                "tiFilter",
                "tiFlagOutline",
                "tiFlag",
                "tiFlashOutline",
                "tiFlash",
                "tiFlowChildren",
                "tiFlowMerge",
                "tiFlowParallel",
                "tiFlowSwitch",
                "tiFolderAdd",
                "tiFolderDelete",
                "tiFolderOpen",
                "tiFolder",
                "tiGift",
                "tiGlobeOutline",
                "tiGlobe",
                "tiGroupOutline",
                "tiGroup",
                "tiHeadphones",
                "tiHeartFullOutline",
                "tiHeartHalfOutline",
                "tiHeartOutline",
                "tiHeart",
                "tiHomeOutline",
                "tiHome",
                "tiHtml5",
                "tiImageOutline",
                "tiImage",
                "tiInfinityOutline",
                "tiInfinity",
                "tiInfoLargeOutline",
                "tiInfoLarge",
                "tiInfoOutline",
                "tiInfo",
                "tiInputCheckedOutline",
                "tiInputChecked",
                "tiKeyOutline",
                "tiKey",
                "tiKeyboard",
                "tiLeaf",
                "tiLightbulb",
                "tiLinkOutline",
                "tiLink",
                "tiLocationArrowOutline",
                "tiLocationArrow",
                "tiLocationOutline",
                "tiLocation",
                "tiLockClosedOutline",
                "tiLockClosed",
                "tiLockOpenOutline",
                "tiLockOpen",
                "tiMail",
                "tiMap",
                "tiMediaEjectOutline",
                "tiMediaEject",
                "tiMediaFastForwardOutline",
                "tiMediaFastForward",
                "tiMediaPauseOutline",
                "tiMediaPause",
                "tiMediaPlayOutline",
                "tiMediaPlayReverseOutline",
                "tiMediaPlayReverse",
                "tiMediaPlay",
                "tiMediaRecordOutline",
                "tiMediaRecord",
                "tiMediaRewindOutline",
                "tiMediaRewind",
                "tiMediaStopOutline",
                "tiMediaStop",
                "tiMessageTyping",
                "tiMessage",
                "tiMessages",
                "tiMicrophoneOutline",
                "tiMicrophone",
                "tiMinusOutline",
                "tiMinus",
                "tiMortarBoard",
                "tiNews",
                "tiNotesOutline",
                "tiNotes",
                "tiPen",
                "tiPencil",
                "tiPhoneOutline",
                "tiPhone",
                "tiPiOutline",
                "tiPi",
                "tiPinOutline",
                "tiPin",
                "tiPipette",
                "tiPlaneOutline",
                "tiPlane",
                "tiPlug",
                "tiPlusOutline",
                "tiPlus",
                "tiPointOfInterestOutline",
                "tiPointOfInterest",
                "tiPowerOutline",
                "tiPower",
                "tiPrinter",
                "tiPuzzleOutline",
                "tiPuzzle",
                "tiRadarOutline",
                "tiRadar",
                "tiRefreshOutline",
                "tiRefresh",
                "tiRssOutline",
                "tiRss",
                "tiScissorsOutline",
                "tiScissors",
                "tiShoppingBag",
                "tiShoppingCart",
                "tiSocialAtCircular",
                "tiSocialDribbbleCircular",
                "tiSocialDribbble",
                "tiSocialFacebookCircular",
                "tiSocialFacebook",
                "tiSocialFlickrCircular",
                "tiSocialFlickr",
                "tiSocialGithubCircular",
                "tiSocialGithub",
                "tiSocialGooglePlusCircular",
                "tiSocialGooglePlus",
                "tiSocialInstagramCircular",
                "tiSocialInstagram",
                "tiSocialLastFmCircular",
                "tiSocialLastFm",
                "tiSocialLinkedinCircular",
                "tiSocialLinkedin",
                "tiSocialPinterestCircular",
                "tiSocialPinterest",
                "tiSocialSkypeOutline",
                "tiSocialSkype",
                "tiSocialTumblerCircular",
                "tiSocialTumbler",
                "tiSocialTwitterCircular",
                "tiSocialTwitter",
                "tiSocialVimeoCircular",
                "tiSocialVimeo",
                "tiSocialYoutubeCircular",
                "tiSocialYoutube",
                "tiSortAlphabeticallyOutline",
                "tiSortAlphabetically",
                "tiSortNumericallyOutline",
                "tiSortNumerically",
                "tiSpannerOutline",
                "tiSpanner",
                "tiSpiral",
                "tiStarFullOutline",
                "tiStarHalfOutline",
                "tiStarHalf",
                "tiStarOutline",
                "tiStar",
                "tiStarburstOutline",
                "tiStarburst",
                "tiStopwatch",
                "tiSupport",
                "tiTabsOutline",
                "tiTag",
                "tiTags",
                "tiThLargeOutline",
                "tiThLarge",
                "tiThListOutline",
                "tiThList",
                "tiThMenuOutline",
                "tiThMenu",
                "tiThSmallOutline",
                "tiThSmall",
                "tiThermometer",
                "tiThumbsDown",
                "tiThumbsOk",
                "tiThumbsUp",
                "tiTickOutline",
                "tiTick",
                "tiTicket",
                "tiTime",
                "tiTimesOutline",
                "tiTimes",
                "tiTrash",
                "tiTree",
                "tiUploadOutline",
                "tiUpload",
                "tiUserAddOutline",
                "tiUserAdd",
                "tiUserDeleteOutline",
                "tiUserDelete",
                "tiUserOutline",
                "tiUser",
                "tiVendorAndroid",
                "tiVendorApple",
                "tiVendorMicrosoft",
                "tiVideoOutline",
                "tiVideo",
                "tiVolumeDown",
                "tiVolumeMute",
                "tiVolumeUp",
                "tiVolume",
                "tiWarningOutline",
                "tiWarning",
                "tiWatch",
                "tiWavesOutline",
                "tiWaves",
                "tiWeatherCloudy",
                "tiWeatherDownpour",
                "tiWeatherNight",
                "tiWeatherPartlySunny",
                "tiWeatherShower",
                "tiWeatherSnow",
                "tiWeatherStormy",
                "tiWeatherSunny",
                "tiWeatherWindyCloudy",
                "tiWeatherWindy",
                "tiWiFiOutline",
                "tiWiFi",
                "tiWine",
                "tiWorldOutline",
                "tiWorld",
                "tiZoomInOutline",
                "tiZoomIn",
                "tiZoomOutOutline",
                "tiZoomOut",
                "tiZoomOutline",
                "tiZoom",
            ],
            "unicode-math": [
                "QED",
                "benzener",
                "checkmark",
                "coloneq",
                "diameter",
                "dicei",
                "diceii",
                "diceiii",
                "diceiv",
                "dicev",
                "dicevi",
                "downwhitearrow",
                "dprime",
                "equcolon",
                "errorbarblackcircle",
                "errorbarblackdiamond",
                "errorbarblacksquare",
                "errorbarcircle",
                "errorbardiamond",
                "errorbarsquare",
                "hermitmatrix",
                "hexagon",
                "increment",
                "lAngle",
                "leftwhitearrow",
                "mapsfrom",
                "mathbb",
                "mathbbit",
                "mathbffrac",
                "mathbfit",
                "mathbfscr",
                "mathbfsfit",
                "mathbfsfup",
                "mathbfup",
                "mathfrak",
                "mathit",
                "mathscr",
                "mathsfit",
                "mathsfup",
                "mathtt",
                "mathup",
                "mitAlpha",
                "mitBeta",
                "mitChi",
                "mitDelta",
                "mitEpsilon",
                "mitEta",
                "mitGamma",
                "mitIota",
                "mitKappa",
                "mitLambda",
                "mitMu",
                "mitNu",
                "mitOmega",
                "mitOmicron",
                "mitPhi",
                "mitPi",
                "mitPsi",
                "mitRho",
                "mitSigma",
                "mitTau",
                "mitTheta",
                "mitUpsilon",
                "mitXi",
                "mitZeta",
                "mitalpha",
                "mitbeta",
                "mitchi",
                "mitdelta",
                "mitepsilon",
                "miteta",
                "mitgamma",
                "mitiota",
                "mitkappa",
                "mitlambda",
                "mitmu",
                "mitnu",
                "mitomega",
                "mitomicron",
                "mitphi",
                "mitpi",
                "mitpsi",
                "mitrho",
                "mitsigma",
                "mittau",
                "mittheta",
                "mitupsilon",
                "mitvarepsilon",
                "mitvarkappa",
                "mitvarphi",
                "mitvarpi",
                "mitvarrho",
                "mitvarsigma",
                "mitvartheta",
                "mitxi",
                "mitzeta",
                "mupAlpha",
                "mupBeta",
                "mupChi",
                "mupDelta",
                "mupEpsilon",
                "mupEta",
                "mupGamma",
                "mupIota",
                "mupKappa",
                "mupLambda",
                "mupMu",
                "mupNu",
                "mupOmega",
                "mupOmicron",
                "mupPhi",
                "mupPi",
                "mupPsi",
                "mupRho",
                "mupSigma",
                "mupTau",
                "mupTheta",
                "mupUpsilon",
                "mupXi",
                "mupZeta",
                "mupalpha",
                "mupbeta",
                "mupchi",
                "mupdelta",
                "mupepsilon",
                "mupeta",
                "mupgamma",
                "mupiota",
                "mupkappa",
                "muplambda",
                "mupmu",
                "mupnu",
                "mupomega",
                "mupomicron",
                "mupphi",
                "muppi",
                "muppsi",
                "muprho",
                "mupsigma",
                "muptau",
                "muptheta",
                "mupupsilon",
                "mupvarphi",
                "mupvarpi",
                "mupvarsigma",
                "mupvartheta",
                "mupxi",
                "mupzeta",
                "napprox",
                "nequiv",
                "nsime",
                "nsubset",
                "nsupset",
                "ocirc",
                "oiiint",
                "oiint",
                "rAngle",
                "rightwhitearrow",
                "setmathfont",
                "setmathfontface",
                "sime",
                "symbb",
                "symbbit",
                "symbf",
                "symbfcal",
                "symbffrak",
                "symbfit",
                "symbfscr",
                "symbfsf",
                "symbfsfit",
                "symbfsfup",
                "symbfup",
                "symcal",
                "symfrak",
                "symit",
                "symliteral",
                "symnormal",
                "symscr",
                "symsf",
                "symsfit",
                "symsfup",
                "symtt",
                "symup",
                "thermod",
                "unimathsetup",
                "updownarrows",
                "upwhitearrow",
                "varhexagonlrbonds",
            ],
            "xcolor": [
                "DefineNamedColor",
                "blendcolors",
                "blendcolors*",
                "boxframe",
                "color",
                "colorbox",
                "colorlet",
                "colormask",
                "colorseriescycle",
                "definecolor",
                "definecolors",
                "definecolorseries",
                "definecolorset",
                "fcolorbox",
                "hiderowcolors",
                "ifdefinecolors",
                "ifglobalcolors",
                "ifmaskcolors",
                "maskcolors",
                "nopagecolor",
                "pagecolor",
                "preparecolor",
                "preparecolorset",
                "providecolor",
                "providecolors",
                "providecolorset",
                "resetcolorseries",
                "rowcolors",
                "rowcolors*",
                "rownum",
                "showrowcolors",
                "testcolor",
                "textcolor",
                "xglobal",
            ],
            "xkeyval": [
                "CurrentOption",
                "define@choicekey",
                "define@choicekey*",
                "define@cmdkey",
                "define@cmdkeys",
                "define@key",
            ],
            "xparse": [
                "ArgumentSpecification",
                "DeclareDocumentCommand",
                "DeclareDocumentEnvironment",
                "DeclareExpandableDocumentCommand",
                "IfBooleanF",
                "IfBooleanT",
                "IfBooleanTF",
                "IfNoValueF",
                "IfNoValueT",
                "IfNoValueTF",
                "IfValueF",
                "IfValueT",
                "IfValueTF",
                "NewDocumentCommand",
                "NewDocumentEnvironment",
                "NewExpandableDocumentCommand",
                "ProvideDocumentCommand",
                "ProvideDocumentEnvironment",
                "ProvideExpandableDocumentCommand",
                "RenewDocumentCommand",
                "RenewDocumentEnvironment",
                "RenewExpandableDocumentCommand",
            ],
            "xspace": [
                "xspace",
            ],
        }
        self._candidates = []
        for pkg, cmds in pkgcmds.items():
            for cmd in cmds:
                self._candidates += [{
                    "word": cmd,
                    "kind": pkg,
                    "abbr": "\\" + cmd,
                }]

    def gather_candidates(self, context):
        if re.search(self.input_pattern, context["input"]):
            return self._candidates
