#!/usr/bin/env python3
import argparse
import os
import re
import subprocess
from pathlib import Path
from tempfile import NamedTemporaryFile


def update(
    vim: str = "nvim",
    *,
    add: str = "en.utf-8.add",
    check: bool = False,
    casesensitive: bool = True,
):
    cmd = [vim, "--clean"]
    if Path(vim).name == "nvim":
        cmd.append("--headless")
    cmd += ["-c", "set spell"]

    subprocess.run(
        cmd
        + [
            "-c",
            "|".join(
                [
                    "2,$sort u",
                    "2,$sort i",
                    "up",
                    "mkspell! %",
                    "q",
                ]
            ),
            add,
        ],
        env=os.environ | {"LANG": "C"},
        check=True,
    )
    if not check:
        return

    with NamedTemporaryFile() as ref:
        subprocess.run(
            cmd
            + [
                "-c",
                "|".join(
                    [
                        "set spell",
                        "spelldump",
                        "keepp 0;2/^#/d",
                        f"w! ++enc=utf-8 {ref.name}",
                        "qa",
                    ]
                ),
            ],
            env=os.environ | {"LANG": "C"},
            check=True,
        )

        pat = re.compile("/[^/]+$")

        newwords = set()
        with open(add) as f:
            for w in f:
                if not w.startswith("#") and not w.startswith("/"):
                    w = pat.sub("", w.strip())
                    newwords.add(w if casesensitive else w.lower())

        with open(ref.name) as f:
            for w in f:
                w = pat.sub("", w.strip())
                if not casesensitive:
                    w = w.lower()
                if w in newwords:
                    print(w)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("vim", nargs="?", default="nvim", help="vim/nvim")
    parser.add_argument("--check", "-c", action="store_true", help="check duplicates")
    args = parser.parse_args()
    update(vim=args.vim, check=args.check)


if __name__ == "__main__":
    main()
