#!/usr/bin/env python3
import argparse
import os
import re
import subprocess
from pathlib import Path
from tempfile import NamedTemporaryFile


def update(
    vim: str = "nvim",
    *,
    add: str = "en.utf-8.add",
    check: bool = False,
    casesensitive: bool = True,
):
    cmd = [vim, "--clean"]
    if Path(vim).name == "nvim":
        cmd.append("--headless")

    with NamedTemporaryFile() as ref:
        cmd += [
            "-c",
            "|".join(
                [
                    "set spell",
                    f"e {add}",
                    "sort u",
                    "sort i",
                    "up",
                    "mkspell! %",
                    "%bw",
                    "spelldump",
                    "keepp 0;2/^#/d",
                    f"w! {ref.name}",
                    "qa",
                ]
            ),
        ]
        os.putenv("LANG", "C")
        subprocess.run(cmd)

        if not check:
            return

        pat = re.compile("/[^/]+$")

        newwords = set()
        with open(add) as f:
            for w in f:
                if not w.startswith("#") and not w.startswith("/"):
                    w = pat.sub("", w.strip())
                    newwords.add(w if casesensitive else w.lower())

        with open(ref.name) as f:
            for w in f:
                w = pat.sub("", w.strip())
                if not casesensitive:
                    w = w.lower()
                if w in newwords:
                    print(w)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("vim", nargs="?", default="nvim", help="vim/nvim")
    parser.add_argument("--check", "-c", action="store_true", help="check duplicates")
    args = parser.parse_args()
    update(vim=args.vim, check=args.check)


if __name__ == "__main__":
    main()
