#!/usr/bin/env python3
import argparse
import json

try:
    import tomllib
except ImportError:
    import toml as tomllib


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("toml", type=argparse.FileType())
    parser.add_argument("json", type=argparse.FileType("w"))
    args = parser.parse_args()
    with args.toml:
        snip = tomllib.loads(args.toml.read())
    with args.json:
        json.dump(snip, args.json)


if __name__ == "__main__":
    main()
