#!/usr/bin/env python3
import json
import logging
import toml
from pathlib import Path


def main():
    logging.basicConfig(level=logging.INFO)
    for file in Path().glob("*.toml"):
        logging.info(file)
        snip = toml.load(file)
        with open(file.name.replace(".toml", ".json"), "w") as f:
            json.dump(snip, f)


if __name__ == "__main__":
    main()
