#!/usr/bin/env python3
import argparse
import json

import yaml


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("yaml", type=argparse.FileType())
    parser.add_argument("json", type=argparse.FileType("w"))
    args = parser.parse_args()
    with args.yaml:
        snip = yaml.load(args.yaml, yaml.SafeLoader)
    with args.json:
        json.dump(snip, args.json)


if __name__ == "__main__":
    main()
