"Language: crystallographic information file (chemical/x-cif)

if exists('b:current_syntax')
  finish
endif

syn case ignore

" https://it.iucr.org/Ga/ch2o2v0001/ {{{1
syn match cifComment /#.*/
syn match cifBlock /data_\S\+/
syn match cifBlock /save_\S\+/
syn match cifString /'.\{-}'/
syn match cifString /".\{-}"/

syn keyword cifBlock loop_
syn keyword cifBlock stop_
syn keyword cifBlock global_

syn match cifSpecial /?/

" https://it.iucr.org/Ga/ch4o1v0001/ {{{1
"_atom_site_[]
syn keyword coreCifDictionary	_atom_site_adp_type
syn keyword coreCifDictionary	_atom_site_aniso_B_11
syn keyword coreCifDictionary	_atom_site_aniso_B_12
syn keyword coreCifDictionary	_atom_site_aniso_B_13
syn keyword coreCifDictionary	_atom_site_aniso_B_22
syn keyword coreCifDictionary	_atom_site_aniso_B_23
syn keyword coreCifDictionary	_atom_site_aniso_B_33
syn keyword coreCifDictionary	_atom_site_aniso_label
syn keyword coreCifDictionary	_atom_site_aniso_ratio
syn keyword coreCifDictionary	_atom_site_aniso_type_symbol
syn keyword coreCifDictionary	_atom_site_aniso_U_11
syn keyword coreCifDictionary	_atom_site_aniso_U_12
syn keyword coreCifDictionary	_atom_site_aniso_U_13
syn keyword coreCifDictionary	_atom_site_aniso_U_22
syn keyword coreCifDictionary	_atom_site_aniso_U_23
syn keyword coreCifDictionary	_atom_site_aniso_U_33
syn keyword coreCifDictionary	_atom_site_attached_hydrogens
syn keyword coreCifDictionary	_atom_site_B_equiv_geom_mean
syn keyword coreCifDictionary	_atom_site_B_iso_or_equiv
syn keyword coreCifDictionary	_atom_site_calc_attached_atom
syn keyword coreCifDictionary	_atom_site_calc_flag
syn keyword coreCifDictionary	_atom_site_Cartn_x
syn keyword coreCifDictionary	_atom_site_Cartn_y
syn keyword coreCifDictionary	_atom_site_Cartn_z
syn keyword coreCifDictionary	_atom_site_chemical_conn_number
syn keyword coreCifDictionary	_atom_site_constraints
syn keyword coreCifDictionary	_atom_site_description
syn keyword coreCifDictionary	_atom_site_disorder_assembly
syn keyword coreCifDictionary	_atom_site_disorder_group
syn keyword coreCifDictionary	_atom_site_fract_x
syn keyword coreCifDictionary	_atom_site_fract_y
syn keyword coreCifDictionary	_atom_site_fract_z
syn keyword coreCifDictionary	_atom_site_label
syn keyword coreCifDictionary	_atom_site_label_component_0
syn keyword coreCifDictionary	_atom_site_label_component_1
syn keyword coreCifDictionary	_atom_site_label_component_2
syn keyword coreCifDictionary	_atom_site_label_component_3
syn keyword coreCifDictionary	_atom_site_label_component_4
syn keyword coreCifDictionary	_atom_site_label_component_5
syn keyword coreCifDictionary	_atom_site_label_component_6
syn keyword coreCifDictionary	_atom_site_occupancy
syn keyword coreCifDictionary	_atom_site_refinement_flags
syn keyword coreCifDictionary	_atom_site_refinement_flags_adp
syn keyword coreCifDictionary	_atom_site_refinement_flags_occupancy
syn keyword coreCifDictionary	_atom_site_refinement_flags_posn
syn keyword coreCifDictionary	_atom_site_restraints
syn keyword coreCifDictionary	_atom_site_symmetry_multiplicity
syn keyword coreCifDictionary	_atom_site_thermal_displace_type
syn keyword coreCifDictionary	_atom_site_type_symbol
syn keyword coreCifDictionary	_atom_site_U_equiv_geom_mean
syn keyword coreCifDictionary	_atom_site_U_iso_or_equiv
syn keyword coreCifDictionary	_atom_site_Wyckoff_symbol
"_atom_sites_[]
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_matrix_11
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_matrix_12
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_matrix_13
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_matrix_21
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_matrix_22
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_matrix_23
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_matrix_31
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_matrix_32
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_matrix_33
syn keyword coreCifDictionary	_atom_sites_Cartn_transform_axes
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_vector_1
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_vector_2
syn keyword coreCifDictionary	_atom_sites_Cartn_tran_vector_3
syn keyword coreCifDictionary	_atom_sites_fract_tran_matrix_11
syn keyword coreCifDictionary	_atom_sites_fract_tran_matrix_12
syn keyword coreCifDictionary	_atom_sites_fract_tran_matrix_13
syn keyword coreCifDictionary	_atom_sites_fract_tran_matrix_21
syn keyword coreCifDictionary	_atom_sites_fract_tran_matrix_22
syn keyword coreCifDictionary	_atom_sites_fract_tran_matrix_23
syn keyword coreCifDictionary	_atom_sites_fract_tran_matrix_31
syn keyword coreCifDictionary	_atom_sites_fract_tran_matrix_32
syn keyword coreCifDictionary	_atom_sites_fract_tran_matrix_33
syn keyword coreCifDictionary	_atom_sites_fract_tran_vector_1
syn keyword coreCifDictionary	_atom_sites_fract_tran_vector_2
syn keyword coreCifDictionary	_atom_sites_fract_tran_vector_3
syn keyword coreCifDictionary	_atom_sites_solution_primary
syn keyword coreCifDictionary	_atom_sites_solution_secondary
syn keyword coreCifDictionary	_atom_sites_solution_hydrogens
syn keyword coreCifDictionary	_atom_sites_special_details
"_atom_type_[]
syn keyword coreCifDictionary	_atom_type_analytical_mass_%
syn keyword coreCifDictionary	_atom_type_description
syn keyword coreCifDictionary	_atom_type_number_in_cell
syn keyword coreCifDictionary	_atom_type_oxidation_number
syn keyword coreCifDictionary	_atom_type_radius_bond
syn keyword coreCifDictionary	_atom_type_radius_contact
syn keyword coreCifDictionary	_atom_type_scat_Cromer_Mann_a1
syn keyword coreCifDictionary	_atom_type_scat_Cromer_Mann_a2
syn keyword coreCifDictionary	_atom_type_scat_Cromer_Mann_a3
syn keyword coreCifDictionary	_atom_type_scat_Cromer_Mann_a4
syn keyword coreCifDictionary	_atom_type_scat_Cromer_Mann_b1
syn keyword coreCifDictionary	_atom_type_scat_Cromer_Mann_b2
syn keyword coreCifDictionary	_atom_type_scat_Cromer_Mann_b3
syn keyword coreCifDictionary	_atom_type_scat_Cromer_Mann_b4
syn keyword coreCifDictionary	_atom_type_scat_Cromer_Mann_c
syn keyword coreCifDictionary	_atom_type_scat_dispersion_imag
syn keyword coreCifDictionary	_atom_type_scat_dispersion_real
syn keyword coreCifDictionary	_atom_type_scat_dispersion_source
syn keyword coreCifDictionary	_atom_type_scat_length_neutron
syn keyword coreCifDictionary	_atom_type_scat_source
syn keyword coreCifDictionary	_atom_type_scat_versus_stol_list
syn keyword coreCifDictionary	_atom_type_symbol
"_audit_[]
syn keyword coreCifDictionary	_audit_block_code
syn keyword coreCifDictionary	_audit_creation_date
syn keyword coreCifDictionary	_audit_creation_method
syn keyword coreCifDictionary	_audit_update_record
"_audit_author_[]
syn keyword coreCifDictionary	_audit_author_address
syn keyword coreCifDictionary	_audit_author_name
"_audit_conform_[]
syn keyword coreCifDictionary	_audit_conform_dict_location
syn keyword coreCifDictionary	_audit_conform_dict_name
syn keyword coreCifDictionary	_audit_conform_dict_version
"_audit_contact_author_[]
syn keyword coreCifDictionary	_audit_contact_author_address
syn keyword coreCifDictionary	_audit_contact_author_email
syn keyword coreCifDictionary	_audit_contact_author_fax
syn keyword coreCifDictionary	_audit_contact_author_name
syn keyword coreCifDictionary	_audit_contact_author_phone
"_audit_link_[]
syn keyword coreCifDictionary	_audit_link_block_code
syn keyword coreCifDictionary	_audit_link_block_description
"_cell_[]
syn keyword coreCifDictionary	_cell_angle_alpha
syn keyword coreCifDictionary	_cell_angle_beta
syn keyword coreCifDictionary	_cell_angle_gamma
syn keyword coreCifDictionary	_cell_formula_units_Z
syn keyword coreCifDictionary	_cell_length_a
syn keyword coreCifDictionary	_cell_length_b
syn keyword coreCifDictionary	_cell_length_c
syn keyword coreCifDictionary	_cell_measurement_pressure
syn keyword coreCifDictionary	_cell_measurement_radiation
syn keyword coreCifDictionary	_cell_measurement_reflns_used
syn keyword coreCifDictionary	_cell_measurement_temperature
syn keyword coreCifDictionary	_cell_measurement_theta_max
syn keyword coreCifDictionary	_cell_measurement_theta_min
syn keyword coreCifDictionary	_cell_measurement_wavelength
syn keyword coreCifDictionary	_cell_reciprocal_angle_alpha
syn keyword coreCifDictionary	_cell_reciprocal_angle_beta
syn keyword coreCifDictionary	_cell_reciprocal_angle_gamma
syn keyword coreCifDictionary	_cell_reciprocal_length_a
syn keyword coreCifDictionary	_cell_reciprocal_length_b
syn keyword coreCifDictionary	_cell_reciprocal_length_c
syn keyword coreCifDictionary	_cell_special_details
syn keyword coreCifDictionary	_cell_volume
"_cell_measurement_refln_[]
syn keyword coreCifDictionary	_cell_measurement_refln_index_h
syn keyword coreCifDictionary	_cell_measurement_refln_index_k
syn keyword coreCifDictionary	_cell_measurement_refln_index_l
syn keyword coreCifDictionary	_cell_measurement_refln_theta
"_chemical_[]
syn keyword coreCifDictionary	_chemical_absolute_configuration
syn keyword coreCifDictionary	_chemical_compound_source
syn keyword coreCifDictionary	_chemical_melting_point
syn keyword coreCifDictionary	_chemical_melting_point_gt
syn keyword coreCifDictionary	_chemical_melting_point_lt
syn keyword coreCifDictionary	_chemical_name_common
syn keyword coreCifDictionary	_chemical_name_mineral
syn keyword coreCifDictionary	_chemical_name_structure_type
syn keyword coreCifDictionary	_chemical_name_systematic
syn keyword coreCifDictionary	_chemical_optical_rotation
syn keyword coreCifDictionary	_chemical_properties_biological
syn keyword coreCifDictionary	_chemical_properties_physical
syn keyword coreCifDictionary	_chemical_temperature_decomposition
syn keyword coreCifDictionary	_chemical_temperature_decomposition_gt
syn keyword coreCifDictionary	_chemical_temperature_decomposition_lt
syn keyword coreCifDictionary	_chemical_temperature_sublimation
syn keyword coreCifDictionary	_chemical_temperature_sublimation_gt
syn keyword coreCifDictionary	_chemical_temperature_sublimation_lt
"_chemical_conn_atom_[]
syn keyword coreCifDictionary	_chemical_conn_atom_charge
syn keyword coreCifDictionary	_chemical_conn_atom_display_x
syn keyword coreCifDictionary	_chemical_conn_atom_display_y
syn keyword coreCifDictionary	_chemical_conn_atom_NCA
syn keyword coreCifDictionary	_chemical_conn_atom_NH
syn keyword coreCifDictionary	_chemical_conn_atom_number
syn keyword coreCifDictionary	_chemical_conn_atom_type_symbol
"_chemical_conn_bond_[]
syn keyword coreCifDictionary	_chemical_conn_bond_atom_1
syn keyword coreCifDictionary	_chemical_conn_bond_atom_2
syn keyword coreCifDictionary	_chemical_conn_bond_type
"_chemical_formula_[]
syn keyword coreCifDictionary	_chemical_formula_analytical
syn keyword coreCifDictionary	_chemical_formula_iupac
syn keyword coreCifDictionary	_chemical_formula_moiety
syn keyword coreCifDictionary	_chemical_formula_structural
syn keyword coreCifDictionary	_chemical_formula_sum
syn keyword coreCifDictionary	_chemical_formula_weight
syn keyword coreCifDictionary	_chemical_formula_weight_meas
"_citation_[]
syn keyword coreCifDictionary	_citation_abstract
syn keyword coreCifDictionary	_citation_abstract_id_CAS
syn keyword coreCifDictionary	_citation_book_id_ISBN
syn keyword coreCifDictionary	_citation_book_publisher
syn keyword coreCifDictionary	_citation_book_publisher_city
syn keyword coreCifDictionary	_citation_book_title
syn keyword coreCifDictionary	_citation_coordinate_linkage
syn keyword coreCifDictionary	_citation_country
syn keyword coreCifDictionary	_citation_database_id_CSD
syn keyword coreCifDictionary	_citation_database_id_Medline
syn keyword coreCifDictionary	_citation_id
syn keyword coreCifDictionary	_citation_journal_abbrev
syn keyword coreCifDictionary	_citation_journal_id_ASTM
syn keyword coreCifDictionary	_citation_journal_id_CSD
syn keyword coreCifDictionary	_citation_journal_id_ISSN
syn keyword coreCifDictionary	_citation_journal_full
syn keyword coreCifDictionary	_citation_journal_issue
syn keyword coreCifDictionary	_citation_journal_volume
syn keyword coreCifDictionary	_citation_language
syn keyword coreCifDictionary	_citation_page_first
syn keyword coreCifDictionary	_citation_page_last
syn keyword coreCifDictionary	_citation_special_details
syn keyword coreCifDictionary	_citation_title
syn keyword coreCifDictionary	_citation_year
"_citation_author_[]
syn keyword coreCifDictionary	_citation_author_citation_id
syn keyword coreCifDictionary	_citation_author_name
syn keyword coreCifDictionary	_citation_author_ordinal
"_citation_editor_[]
syn keyword coreCifDictionary	_citation_editor_citation_id
syn keyword coreCifDictionary	_citation_editor_name
syn keyword coreCifDictionary	_citation_editor_ordinal
"_computing_[]
syn keyword coreCifDictionary	_computing_cell_refinement
syn keyword coreCifDictionary	_computing_data_collection
syn keyword coreCifDictionary	_computing_data_reduction
syn keyword coreCifDictionary	_computing_molecular_graphics
syn keyword coreCifDictionary	_computing_publication_material
syn keyword coreCifDictionary	_computing_structure_refinement
syn keyword coreCifDictionary	_computing_structure_solution
"_database_[]
syn keyword coreCifDictionary	_database_code_CAS
syn keyword coreCifDictionary	_database_code_CSD
syn keyword coreCifDictionary	_database_code_ICSD
syn keyword coreCifDictionary	_database_code_MDF
syn keyword coreCifDictionary	_database_code_NBS
syn keyword coreCifDictionary	_database_code_PDB
syn keyword coreCifDictionary	_database_code_PDF
syn keyword coreCifDictionary	_database_code_depnum_ccdc_fiz
syn keyword coreCifDictionary	_database_code_depnum_ccdc_journal
syn keyword coreCifDictionary	_database_code_depnum_ccdc_archive
syn keyword coreCifDictionary	_database_CSD_history
syn keyword coreCifDictionary	_database_journal_ASTM
syn keyword coreCifDictionary	_database_journal_CSD
"_diffrn_[]
syn keyword coreCifDictionary	_diffrn_ambient_environment
syn keyword coreCifDictionary	_diffrn_ambient_pressure
syn keyword coreCifDictionary	_diffrn_ambient_pressure_gt
syn keyword coreCifDictionary	_diffrn_ambient_pressure_lt
syn keyword coreCifDictionary	_diffrn_ambient_temperature
syn keyword coreCifDictionary	_diffrn_ambient_temperature_gt
syn keyword coreCifDictionary	_diffrn_ambient_temperature_lt
syn keyword coreCifDictionary	_diffrn_crystal_treatment
syn keyword coreCifDictionary	_diffrn_measured_fraction_theta_full
syn keyword coreCifDictionary	_diffrn_measured_fraction_theta_max
syn keyword coreCifDictionary	_diffrn_special_details
syn keyword coreCifDictionary	_diffrn_symmetry_description
"_diffrn_attenuator_[]
syn keyword coreCifDictionary	_diffrn_attenuator_code
syn keyword coreCifDictionary	_diffrn_attenuator_material
syn keyword coreCifDictionary	_diffrn_attenuator_scale
"_diffrn_detector_[]
syn keyword coreCifDictionary	_diffrn_detector
syn keyword coreCifDictionary	_diffrn_detector_area_resol_mean
syn keyword coreCifDictionary	_diffrn_detector_details
syn keyword coreCifDictionary	_diffrn_detector_dtime
syn keyword coreCifDictionary	_diffrn_detector_type
syn keyword coreCifDictionary	_diffrn_radiation_detector
syn keyword coreCifDictionary	_diffrn_radiation_detector_dtime
"_diffrn_measurement_[]
syn keyword coreCifDictionary	_diffrn_measurement_details
syn keyword coreCifDictionary	_diffrn_measurement_device
syn keyword coreCifDictionary	_diffrn_measurement_device_details
syn keyword coreCifDictionary	_diffrn_measurement_device_type
syn keyword coreCifDictionary	_diffrn_measurement_method
syn keyword coreCifDictionary	_diffrn_measurement_specimen_support
"_diffrn_orient_matrix_[]
syn keyword coreCifDictionary	_diffrn_orient_matrix_type
syn keyword coreCifDictionary	_diffrn_orient_matrix_UB_11
syn keyword coreCifDictionary	_diffrn_orient_matrix_UB_12
syn keyword coreCifDictionary	_diffrn_orient_matrix_UB_13
syn keyword coreCifDictionary	_diffrn_orient_matrix_UB_21
syn keyword coreCifDictionary	_diffrn_orient_matrix_UB_22
syn keyword coreCifDictionary	_diffrn_orient_matrix_UB_23
syn keyword coreCifDictionary	_diffrn_orient_matrix_UB_31
syn keyword coreCifDictionary	_diffrn_orient_matrix_UB_32
syn keyword coreCifDictionary	_diffrn_orient_matrix_UB_33
"_diffrn_orient_refln_[]
syn keyword coreCifDictionary	_diffrn_orient_refln_angle_chi
syn keyword coreCifDictionary	_diffrn_orient_refln_angle_kappa
syn keyword coreCifDictionary	_diffrn_orient_refln_angle_omega
syn keyword coreCifDictionary	_diffrn_orient_refln_angle_phi
syn keyword coreCifDictionary	_diffrn_orient_refln_angle_psi
syn keyword coreCifDictionary	_diffrn_orient_refln_angle_theta
syn keyword coreCifDictionary	_diffrn_orient_refln_index_h
syn keyword coreCifDictionary	_diffrn_orient_refln_index_k
syn keyword coreCifDictionary	_diffrn_orient_refln_index_l
"_diffrn_radiation_[]
syn keyword coreCifDictionary	_diffrn_radiation_collimation
syn keyword coreCifDictionary	_diffrn_radiation_filter_edge
syn keyword coreCifDictionary	_diffrn_radiation_inhomogeneity
syn keyword coreCifDictionary	_diffrn_radiation_monochromator
syn keyword coreCifDictionary	_diffrn_radiation_polarisn_norm
syn keyword coreCifDictionary	_diffrn_radiation_polarisn_ratio
syn keyword coreCifDictionary	_diffrn_radiation_probe
syn keyword coreCifDictionary	_diffrn_radiation_type
syn keyword coreCifDictionary	_diffrn_radiation_xray_symbol
"_diffrn_radiation_wavelength_[]
syn keyword coreCifDictionary	_diffrn_radiation_wavelength
syn keyword coreCifDictionary	_diffrn_radiation_wavelength_id
syn keyword coreCifDictionary	_diffrn_radiation_wavelength_wt
"_diffrn_refln_[]
syn keyword coreCifDictionary	_diffrn_refln_angle_chi
syn keyword coreCifDictionary	_diffrn_refln_angle_kappa
syn keyword coreCifDictionary	_diffrn_refln_angle_omega
syn keyword coreCifDictionary	_diffrn_refln_angle_phi
syn keyword coreCifDictionary	_diffrn_refln_angle_psi
syn keyword coreCifDictionary	_diffrn_refln_angle_theta
syn keyword coreCifDictionary	_diffrn_refln_attenuator_code
syn keyword coreCifDictionary	_diffrn_refln_class_code
syn keyword coreCifDictionary	_diffrn_refln_counts_bg_1
syn keyword coreCifDictionary	_diffrn_refln_counts_bg_2
syn keyword coreCifDictionary	_diffrn_refln_counts_net
syn keyword coreCifDictionary	_diffrn_refln_counts_peak
syn keyword coreCifDictionary	_diffrn_refln_counts_total
syn keyword coreCifDictionary	_diffrn_refln_crystal_id
syn keyword coreCifDictionary	_diffrn_refln_detect_slit_horiz
syn keyword coreCifDictionary	_diffrn_refln_detect_slit_vert
syn keyword coreCifDictionary	_diffrn_refln_elapsed_time
syn keyword coreCifDictionary	_diffrn_refln_index_h
syn keyword coreCifDictionary	_diffrn_refln_index_k
syn keyword coreCifDictionary	_diffrn_refln_index_l
syn keyword coreCifDictionary	_diffrn_refln_intensity_net
syn keyword coreCifDictionary	_diffrn_refln_intensity_sigma
syn keyword coreCifDictionary	_diffrn_refln_intensity_u
syn keyword coreCifDictionary	_diffrn_refln_scale_group_code
syn keyword coreCifDictionary	_diffrn_refln_scan_mode
syn keyword coreCifDictionary	_diffrn_refln_scan_mode_backgd
syn keyword coreCifDictionary	_diffrn_refln_scan_rate
syn keyword coreCifDictionary	_diffrn_refln_scan_time_backgd
syn keyword coreCifDictionary	_diffrn_refln_scan_width
syn keyword coreCifDictionary	_diffrn_refln_sint/lambda
syn keyword coreCifDictionary	_diffrn_refln_standard_code
syn keyword coreCifDictionary	_diffrn_refln_wavelength
syn keyword coreCifDictionary	_diffrn_refln_wavelength_id
"_diffrn_reflns_[]
syn keyword coreCifDictionary	_diffrn_reflns_av_R_equivalents
syn keyword coreCifDictionary	_diffrn_reflns_av_sigmaI/netI
syn keyword coreCifDictionary	_diffrn_reflns_av_unetI/netI
syn keyword coreCifDictionary	_diffrn_reflns_limit_h_max
syn keyword coreCifDictionary	_diffrn_reflns_limit_h_min
syn keyword coreCifDictionary	_diffrn_reflns_limit_k_max
syn keyword coreCifDictionary	_diffrn_reflns_limit_k_min
syn keyword coreCifDictionary	_diffrn_reflns_limit_l_max
syn keyword coreCifDictionary	_diffrn_reflns_limit_l_min
syn keyword coreCifDictionary	_diffrn_reflns_number
syn keyword coreCifDictionary	_diffrn_reflns_reduction_process
syn keyword coreCifDictionary	_diffrn_reflns_resolution_full
syn keyword coreCifDictionary	_diffrn_reflns_resolution_max
syn keyword coreCifDictionary	_diffrn_reflns_theta_full
syn keyword coreCifDictionary	_diffrn_reflns_theta_max
syn keyword coreCifDictionary	_diffrn_reflns_theta_min
syn keyword coreCifDictionary	_diffrn_reflns_transf_matrix_11
syn keyword coreCifDictionary	_diffrn_reflns_transf_matrix_12
syn keyword coreCifDictionary	_diffrn_reflns_transf_matrix_13
syn keyword coreCifDictionary	_diffrn_reflns_transf_matrix_21
syn keyword coreCifDictionary	_diffrn_reflns_transf_matrix_22
syn keyword coreCifDictionary	_diffrn_reflns_transf_matrix_23
syn keyword coreCifDictionary	_diffrn_reflns_transf_matrix_31
syn keyword coreCifDictionary	_diffrn_reflns_transf_matrix_32
syn keyword coreCifDictionary	_diffrn_reflns_transf_matrix_33
"_diffrn_reflns_class_[]
syn keyword coreCifDictionary	_diffrn_reflns_class_av_R_eq
syn keyword coreCifDictionary	_diffrn_reflns_class_av_sgI/I
syn keyword coreCifDictionary	_diffrn_reflns_class_av_uI/I
syn keyword coreCifDictionary	_diffrn_reflns_class_code
syn keyword coreCifDictionary	_diffrn_reflns_class_description
syn keyword coreCifDictionary	_diffrn_reflns_class_d_res_high
syn keyword coreCifDictionary	_diffrn_reflns_class_d_res_low
syn keyword coreCifDictionary	_diffrn_reflns_class_number
"_diffrn_scale_group_[]
syn keyword coreCifDictionary	_diffrn_scale_group_code
syn keyword coreCifDictionary	_diffrn_scale_group_I_net
"_diffrn_source_[]
syn keyword coreCifDictionary	_diffrn_radiation_source
syn keyword coreCifDictionary	_diffrn_source
syn keyword coreCifDictionary	_diffrn_source_current
syn keyword coreCifDictionary	_diffrn_source_details
syn keyword coreCifDictionary	_diffrn_source_power
syn keyword coreCifDictionary	_diffrn_source_size
syn keyword coreCifDictionary	_diffrn_source_take-off_angle
syn keyword coreCifDictionary	_diffrn_source_target
syn keyword coreCifDictionary	_diffrn_source_type
syn keyword coreCifDictionary	_diffrn_source_voltage
"_diffrn_standard_refln_[]
syn keyword coreCifDictionary	_diffrn_standard_refln_code
syn keyword coreCifDictionary	_diffrn_standard_refln_index_h
syn keyword coreCifDictionary	_diffrn_standard_refln_index_k
syn keyword coreCifDictionary	_diffrn_standard_refln_index_l
"_diffrn_standards_[]
syn keyword coreCifDictionary	_diffrn_standards_decay_%
syn keyword coreCifDictionary	_diffrn_standards_interval_count
syn keyword coreCifDictionary	_diffrn_standards_interval_time
syn keyword coreCifDictionary	_diffrn_standards_number
syn keyword coreCifDictionary	_diffrn_standards_scale_sigma
syn keyword coreCifDictionary	_diffrn_standards_scale_u
"_exptl_[]
syn keyword coreCifDictionary	_exptl_absorpt_coefficient_mu
syn keyword coreCifDictionary	_exptl_absorpt_correction_T_max
syn keyword coreCifDictionary	_exptl_absorpt_correction_T_min
syn keyword coreCifDictionary	_exptl_absorpt_correction_type
syn keyword coreCifDictionary	_exptl_absorpt_process_details
syn keyword coreCifDictionary	_exptl_crystals_number
syn keyword coreCifDictionary	_exptl_special_details
"_exptl_crystal_[]
syn keyword coreCifDictionary	_exptl_crystal_colour
syn keyword coreCifDictionary	_exptl_crystal_colour_lustre
syn keyword coreCifDictionary	_exptl_crystal_colour_modifier
syn keyword coreCifDictionary	_exptl_crystal_colour_primary
syn keyword coreCifDictionary	_exptl_crystal_density_diffrn
syn keyword coreCifDictionary	_exptl_crystal_density_meas
syn keyword coreCifDictionary	_exptl_crystal_density_meas_gt
syn keyword coreCifDictionary	_exptl_crystal_density_meas_lt
syn keyword coreCifDictionary	_exptl_crystal_density_meas_temp
syn keyword coreCifDictionary	_exptl_crystal_density_meas_temp_gt
syn keyword coreCifDictionary	_exptl_crystal_density_meas_temp_lt
syn keyword coreCifDictionary	_exptl_crystal_density_method
syn keyword coreCifDictionary	_exptl_crystal_description
syn keyword coreCifDictionary	_exptl_crystal_F_000
syn keyword coreCifDictionary	_exptl_crystal_id
syn keyword coreCifDictionary	_exptl_crystal_preparation
syn keyword coreCifDictionary	_exptl_crystal_pressure_history
syn keyword coreCifDictionary	_exptl_crystal_recrystallization_method
syn keyword coreCifDictionary	_exptl_crystal_size_length
syn keyword coreCifDictionary	_exptl_crystal_size_max
syn keyword coreCifDictionary	_exptl_crystal_size_mid
syn keyword coreCifDictionary	_exptl_crystal_size_min
syn keyword coreCifDictionary	_exptl_crystal_size_rad
syn keyword coreCifDictionary	_exptl_crystal_thermal_history
"_exptl_crystal_face_[]
syn keyword coreCifDictionary	_exptl_crystal_face_diffr_chi
syn keyword coreCifDictionary	_exptl_crystal_face_diffr_kappa
syn keyword coreCifDictionary	_exptl_crystal_face_diffr_phi
syn keyword coreCifDictionary	_exptl_crystal_face_diffr_psi
syn keyword coreCifDictionary	_exptl_crystal_face_index_h
syn keyword coreCifDictionary	_exptl_crystal_face_index_k
syn keyword coreCifDictionary	_exptl_crystal_face_index_l
syn keyword coreCifDictionary	_exptl_crystal_face_perp_dist
"_geom_[]
syn keyword coreCifDictionary	_geom_special_details
"_geom_angle_[]
syn keyword coreCifDictionary	_geom_angle
syn keyword coreCifDictionary	_geom_angle_atom_site_label_1
syn keyword coreCifDictionary	_geom_angle_atom_site_label_2
syn keyword coreCifDictionary	_geom_angle_atom_site_label_3
syn keyword coreCifDictionary	_geom_angle_publ_flag
syn keyword coreCifDictionary	_geom_angle_site_symmetry_1
syn keyword coreCifDictionary	_geom_angle_site_symmetry_2
syn keyword coreCifDictionary	_geom_angle_site_symmetry_3
"_geom_bond_[]
syn keyword coreCifDictionary	_geom_bond_atom_site_label_1
syn keyword coreCifDictionary	_geom_bond_atom_site_label_2
syn keyword coreCifDictionary	_geom_bond_distance
syn keyword coreCifDictionary	_geom_bond_publ_flag
syn keyword coreCifDictionary	_geom_bond_site_symmetry_1
syn keyword coreCifDictionary	_geom_bond_site_symmetry_2
syn keyword coreCifDictionary	_geom_bond_valence
"_geom_contact_[]
syn keyword coreCifDictionary	_geom_contact_atom_site_label_1
syn keyword coreCifDictionary	_geom_contact_atom_site_label_2
syn keyword coreCifDictionary	_geom_contact_distance
syn keyword coreCifDictionary	_geom_contact_publ_flag
syn keyword coreCifDictionary	_geom_contact_site_symmetry_1
syn keyword coreCifDictionary	_geom_contact_site_symmetry_2
"_geom_hbond_[]
syn keyword coreCifDictionary	_geom_hbond_angle_DHA
syn keyword coreCifDictionary	_geom_hbond_atom_site_label_D
syn keyword coreCifDictionary	_geom_hbond_atom_site_label_H
syn keyword coreCifDictionary	_geom_hbond_atom_site_label_A
syn keyword coreCifDictionary	_geom_hbond_distance_DH
syn keyword coreCifDictionary	_geom_hbond_distance_HA
syn keyword coreCifDictionary	_geom_hbond_distance_DA
syn keyword coreCifDictionary	_geom_hbond_publ_flag
syn keyword coreCifDictionary	_geom_hbond_site_symmetry_D
syn keyword coreCifDictionary	_geom_hbond_site_symmetry_H
syn keyword coreCifDictionary	_geom_hbond_site_symmetry_A
"_geom_torsion_[]
syn keyword coreCifDictionary	_geom_torsion
syn keyword coreCifDictionary	_geom_torsion_atom_site_label_1
syn keyword coreCifDictionary	_geom_torsion_atom_site_label_2
syn keyword coreCifDictionary	_geom_torsion_atom_site_label_3
syn keyword coreCifDictionary	_geom_torsion_atom_site_label_4
syn keyword coreCifDictionary	_geom_torsion_publ_flag
syn keyword coreCifDictionary	_geom_torsion_site_symmetry_1
syn keyword coreCifDictionary	_geom_torsion_site_symmetry_2
syn keyword coreCifDictionary	_geom_torsion_site_symmetry_3
syn keyword coreCifDictionary	_geom_torsion_site_symmetry_4
"_journal_[]
syn keyword coreCifDictionary	_journal_coden_ASTM
syn keyword coreCifDictionary	_journal_coden_Cambridge
syn keyword coreCifDictionary	_journal_coeditor_address
syn keyword coreCifDictionary	_journal_coeditor_code
syn keyword coreCifDictionary	_journal_coeditor_email
syn keyword coreCifDictionary	_journal_coeditor_fax
syn keyword coreCifDictionary	_journal_coeditor_name
syn keyword coreCifDictionary	_journal_coeditor_notes
syn keyword coreCifDictionary	_journal_coeditor_phone
syn keyword coreCifDictionary	_journal_data_validation_number
syn keyword coreCifDictionary	_journal_date_accepted
syn keyword coreCifDictionary	_journal_date_from_coeditor
syn keyword coreCifDictionary	_journal_date_to_coeditor
syn keyword coreCifDictionary	_journal_date_printers_final
syn keyword coreCifDictionary	_journal_date_printers_first
syn keyword coreCifDictionary	_journal_date_proofs_in
syn keyword coreCifDictionary	_journal_date_proofs_out
syn keyword coreCifDictionary	_journal_date_recd_copyright
syn keyword coreCifDictionary	_journal_date_recd_electronic
syn keyword coreCifDictionary	_journal_date_recd_hard_copy
syn keyword coreCifDictionary	_journal_issue
syn keyword coreCifDictionary	_journal_language
syn keyword coreCifDictionary	_journal_name_full
syn keyword coreCifDictionary	_journal_page_first
syn keyword coreCifDictionary	_journal_page_last
syn keyword coreCifDictionary	_journal_paper_category
syn keyword coreCifDictionary	_journal_suppl_publ_number
syn keyword coreCifDictionary	_journal_suppl_publ_pages
syn keyword coreCifDictionary	_journal_techeditor_address
syn keyword coreCifDictionary	_journal_techeditor_code
syn keyword coreCifDictionary	_journal_techeditor_email
syn keyword coreCifDictionary	_journal_techeditor_fax
syn keyword coreCifDictionary	_journal_techeditor_name
syn keyword coreCifDictionary	_journal_techeditor_notes
syn keyword coreCifDictionary	_journal_techeditor_phone
syn keyword coreCifDictionary	_journal_volume
syn keyword coreCifDictionary	_journal_year
"_journal_index_[]
syn keyword coreCifDictionary	_journal_index_subterm
syn keyword coreCifDictionary	_journal_index_term
syn keyword coreCifDictionary	_journal_index_type
"_publ_[]
syn keyword coreCifDictionary	_publ_contact_author
syn keyword coreCifDictionary	_publ_contact_author_address
syn keyword coreCifDictionary	_publ_contact_author_email
syn keyword coreCifDictionary	_publ_contact_author_fax
syn keyword coreCifDictionary	_publ_contact_author_id_iucr
syn keyword coreCifDictionary	_publ_contact_author_name
syn keyword coreCifDictionary	_publ_contact_author_phone
syn keyword coreCifDictionary	_publ_contact_letter
syn keyword coreCifDictionary	_publ_manuscript_creation
syn keyword coreCifDictionary	_publ_manuscript_processed
syn keyword coreCifDictionary	_publ_manuscript_text
syn keyword coreCifDictionary	_publ_requested_category
syn keyword coreCifDictionary	_publ_requested_coeditor_name
syn keyword coreCifDictionary	_publ_requested_journal
syn keyword coreCifDictionary	_publ_section_title
syn keyword coreCifDictionary	_publ_section_title_footnote
syn keyword coreCifDictionary	_publ_section_synopsis
syn keyword coreCifDictionary	_publ_section_abstract
syn keyword coreCifDictionary	_publ_section_comment
syn keyword coreCifDictionary	_publ_section_introduction
syn keyword coreCifDictionary	_publ_section_experimental
syn keyword coreCifDictionary	_publ_section_exptl_prep
syn keyword coreCifDictionary	_publ_section_exptl_refinement
syn keyword coreCifDictionary	_publ_section_exptl_solution
syn keyword coreCifDictionary	_publ_section_discussion
syn keyword coreCifDictionary	_publ_section_acknowledgements
syn keyword coreCifDictionary	_publ_section_references
syn keyword coreCifDictionary	_publ_section_figure_captions
syn keyword coreCifDictionary	_publ_section_table_legends
"_publ_author_[]
syn keyword coreCifDictionary	_publ_author_address
syn keyword coreCifDictionary	_publ_author_footnote
syn keyword coreCifDictionary	_publ_author_email
syn keyword coreCifDictionary	_publ_author_id_iucr
syn keyword coreCifDictionary	_publ_author_name
"_publ_body_[]
syn keyword coreCifDictionary	_publ_body_contents
syn keyword coreCifDictionary	_publ_body_element
syn keyword coreCifDictionary	_publ_body_format
syn keyword coreCifDictionary	_publ_body_label
syn keyword coreCifDictionary	_publ_body_title
"_publ_manuscript_incl_[]
syn keyword coreCifDictionary	_publ_manuscript_incl_extra_defn
syn keyword coreCifDictionary	_publ_manuscript_incl_extra_info
syn keyword coreCifDictionary	_publ_manuscript_incl_extra_item
"_refine_[]
syn keyword coreCifDictionary	_refine_diff_density_max
syn keyword coreCifDictionary	_refine_diff_density_min
syn keyword coreCifDictionary	_refine_diff_density_rms
syn keyword coreCifDictionary	_refine_ls_abs_structure_details
syn keyword coreCifDictionary	_refine_ls_abs_structure_Flack
syn keyword coreCifDictionary	_refine_ls_abs_structure_Rogers
syn keyword coreCifDictionary	_refine_ls_d_res_high
syn keyword coreCifDictionary	_refine_ls_d_res_low
syn keyword coreCifDictionary	_refine_ls_extinction_coef
syn keyword coreCifDictionary	_refine_ls_extinction_expression
syn keyword coreCifDictionary	_refine_ls_extinction_method
syn keyword coreCifDictionary	_refine_ls_goodness_of_fit_all
syn keyword coreCifDictionary	_refine_ls_goodness_of_fit_gt
syn keyword coreCifDictionary	_refine_ls_goodness_of_fit_obs
syn keyword coreCifDictionary	_refine_ls_goodness_of_fit_ref
syn keyword coreCifDictionary	_refine_ls_hydrogen_treatment
syn keyword coreCifDictionary	_refine_ls_matrix_type
syn keyword coreCifDictionary	_refine_ls_number_constraints
syn keyword coreCifDictionary	_refine_ls_number_parameters
syn keyword coreCifDictionary	_refine_ls_number_reflns
syn keyword coreCifDictionary	_refine_ls_number_restraints
syn keyword coreCifDictionary	_refine_ls_R_factor_all
syn keyword coreCifDictionary	_refine_ls_R_factor_gt
syn keyword coreCifDictionary	_refine_ls_R_factor_obs
syn keyword coreCifDictionary	_refine_ls_R_Fsqd_factor
syn keyword coreCifDictionary	_refine_ls_R_I_factor
syn keyword coreCifDictionary	_refine_ls_restrained_S_all
syn keyword coreCifDictionary	_refine_ls_restrained_S_gt
syn keyword coreCifDictionary	_refine_ls_restrained_S_obs
syn keyword coreCifDictionary	_refine_ls_shift/esd_max
syn keyword coreCifDictionary	_refine_ls_shift/esd_mean
syn keyword coreCifDictionary	_refine_ls_shift/su_max
syn keyword coreCifDictionary	_refine_ls_shift/su_max_lt
syn keyword coreCifDictionary	_refine_ls_shift/su_mean
syn keyword coreCifDictionary	_refine_ls_shift/su_mean_lt
syn keyword coreCifDictionary	_refine_ls_structure_factor_coef
syn keyword coreCifDictionary	_refine_ls_weighting_details
syn keyword coreCifDictionary	_refine_ls_weighting_scheme
syn keyword coreCifDictionary	_refine_ls_wR_factor_all
syn keyword coreCifDictionary	_refine_ls_wR_factor_gt
syn keyword coreCifDictionary	_refine_ls_wR_factor_obs
syn keyword coreCifDictionary	_refine_ls_wR_factor_ref
syn keyword coreCifDictionary	_refine_special_details
"_refine_ls_class_[]
syn keyword coreCifDictionary	_refine_ls_class_code
syn keyword coreCifDictionary	_refine_ls_class_d_res_high
syn keyword coreCifDictionary	_refine_ls_class_d_res_low
syn keyword coreCifDictionary	_refine_ls_class_R_factor_all
syn keyword coreCifDictionary	_refine_ls_class_R_factor_gt
syn keyword coreCifDictionary	_refine_ls_class_R_Fsqd_factor
syn keyword coreCifDictionary	_refine_ls_class_R_I_factor
syn keyword coreCifDictionary	_refine_ls_class_wR_factor_all
"_refln_[]
syn keyword coreCifDictionary	_refln_A_calc
syn keyword coreCifDictionary	_refln_A_meas
syn keyword coreCifDictionary	_refln_B_calc
syn keyword coreCifDictionary	_refln_B_meas
syn keyword coreCifDictionary	_refln_class_code
syn keyword coreCifDictionary	_refln_d_spacing
syn keyword coreCifDictionary	_refln_crystal_id
syn keyword coreCifDictionary	_refln_F_calc
syn keyword coreCifDictionary	_refln_F_meas
syn keyword coreCifDictionary	_refln_F_sigma
syn keyword coreCifDictionary	_refln_F_squared_calc
syn keyword coreCifDictionary	_refln_F_squared_meas
syn keyword coreCifDictionary	_refln_F_squared_sigma
syn keyword coreCifDictionary	_refln_include_status
syn keyword coreCifDictionary	_refln_index_h
syn keyword coreCifDictionary	_refln_index_k
syn keyword coreCifDictionary	_refln_index_l
syn keyword coreCifDictionary	_refln_intensity_calc
syn keyword coreCifDictionary	_refln_intensity_meas
syn keyword coreCifDictionary	_refln_intensity_sigma
syn keyword coreCifDictionary	_refln_mean_path_length_tbar
syn keyword coreCifDictionary	_refln_observed_status
syn keyword coreCifDictionary	_refln_phase_calc
syn keyword coreCifDictionary	_refln_phase_meas
syn keyword coreCifDictionary	_refln_refinement_status
syn keyword coreCifDictionary	_refln_scale_group_code
syn keyword coreCifDictionary	_refln_sint/lambda
syn keyword coreCifDictionary	_refln_symmetry_epsilon
syn keyword coreCifDictionary	_refln_symmetry_multiplicity
syn keyword coreCifDictionary	_refln_wavelength
syn keyword coreCifDictionary	_refln_wavelength_id
"_reflns_[]
syn keyword coreCifDictionary	_reflns_d_resolution_high
syn keyword coreCifDictionary	_reflns_d_resolution_low
syn keyword coreCifDictionary	_reflns_Friedel_coverage
syn keyword coreCifDictionary	_reflns_limit_h_max
syn keyword coreCifDictionary	_reflns_limit_h_min
syn keyword coreCifDictionary	_reflns_limit_k_max
syn keyword coreCifDictionary	_reflns_limit_k_min
syn keyword coreCifDictionary	_reflns_limit_l_max
syn keyword coreCifDictionary	_reflns_limit_l_min
syn keyword coreCifDictionary	_reflns_number_gt
syn keyword coreCifDictionary	_reflns_number_observed
syn keyword coreCifDictionary	_reflns_number_total
syn keyword coreCifDictionary	_reflns_observed_criterion
syn keyword coreCifDictionary	_reflns_special_details
syn keyword coreCifDictionary	_reflns_threshold_expression
"_reflns_class_[]
syn keyword coreCifDictionary	_reflns_class_code
syn keyword coreCifDictionary	_reflns_class_description
syn keyword coreCifDictionary	_reflns_class_d_res_high
syn keyword coreCifDictionary	_reflns_class_d_res_low
syn keyword coreCifDictionary	_reflns_class_number_gt
syn keyword coreCifDictionary	_reflns_class_number_total
syn keyword coreCifDictionary	_reflns_class_R_factor_all
syn keyword coreCifDictionary	_reflns_class_R_factor_gt
syn keyword coreCifDictionary	_reflns_class_R_Fsqd_factor
syn keyword coreCifDictionary	_reflns_class_R_I_factor
syn keyword coreCifDictionary	_reflns_class_wR_factor_all
"_reflns_scale_[]
syn keyword coreCifDictionary	_reflns_scale_group_code
syn keyword coreCifDictionary	_reflns_scale_meas_F
syn keyword coreCifDictionary	_reflns_scale_meas_F_squared
syn keyword coreCifDictionary	_reflns_scale_meas_intensity
"_reflns_shell_[]
syn keyword coreCifDictionary	_reflns_shell_d_res_high
syn keyword coreCifDictionary	_reflns_shell_d_res_low
syn keyword coreCifDictionary	_reflns_shell_meanI_over_sigI_all
syn keyword coreCifDictionary	_reflns_shell_meanI_over_sigI_gt
syn keyword coreCifDictionary	_reflns_shell_meanI_over_sigI_obs
syn keyword coreCifDictionary	_reflns_shell_meanI_over_uI_all
syn keyword coreCifDictionary	_reflns_shell_meanI_over_uI_gt
syn keyword coreCifDictionary	_reflns_shell_number_measured_all
syn keyword coreCifDictionary	_reflns_shell_number_measured_gt
syn keyword coreCifDictionary	_reflns_shell_number_measured_obs
syn keyword coreCifDictionary	_reflns_shell_number_possible
syn keyword coreCifDictionary	_reflns_shell_number_unique_all
syn keyword coreCifDictionary	_reflns_shell_number_unique_gt
syn keyword coreCifDictionary	_reflns_shell_number_unique_obs
syn keyword coreCifDictionary	_reflns_shell_percent_possible_all
syn keyword coreCifDictionary	_reflns_shell_percent_possible_gt
syn keyword coreCifDictionary	_reflns_shell_percent_possible_obs
syn keyword coreCifDictionary	_reflns_shell_Rmerge_F_all
syn keyword coreCifDictionary	_reflns_shell_Rmerge_F_gt
syn keyword coreCifDictionary	_reflns_shell_Rmerge_F_obs
syn keyword coreCifDictionary	_reflns_shell_Rmerge_I_all
syn keyword coreCifDictionary	_reflns_shell_Rmerge_I_gt
syn keyword coreCifDictionary	_reflns_shell_Rmerge_I_obs
"_space_group_[]
syn keyword coreCifDictionary	_space_group_crystal_system
syn keyword coreCifDictionary	_space_group_id
syn keyword coreCifDictionary	_space_group_IT_number
syn keyword coreCifDictionary	_space_group_name_Hall
syn keyword coreCifDictionary	_space_group_name_H-M_alt
"_space_group_symop_[]
syn keyword coreCifDictionary	_space_group_symop_id
syn keyword coreCifDictionary	_space_group_symop_operation_xyz
syn keyword coreCifDictionary	_space_group_symop_sg_id
"_symmetry_[]
syn keyword coreCifDictionary	_symmetry_cell_setting
syn keyword coreCifDictionary	_symmetry_Int_Tables_number
syn keyword coreCifDictionary	_symmetry_space_group_name_Hall
syn keyword coreCifDictionary	_symmetry_space_group_name_H-M
"_symmetry_equiv_[]
syn keyword coreCifDictionary	_symmetry_equiv_pos_as_xyz
syn keyword coreCifDictionary	_symmetry_equiv_pos_site_id
"_valence_param_[]
syn keyword coreCifDictionary	_valence_param_atom_1
syn keyword coreCifDictionary	_valence_param_atom_1_valence
syn keyword coreCifDictionary	_valence_param_atom_2
syn keyword coreCifDictionary	_valence_param_atom_2_valence
syn keyword coreCifDictionary	_valence_param_B
syn keyword coreCifDictionary	_valence_param_details
syn keyword coreCifDictionary	_valence_param_id
syn keyword coreCifDictionary	_valence_param_ref_id
syn keyword coreCifDictionary	_valence_param_Ro
"_valence_ref_[]
syn keyword coreCifDictionary	_valence_ref_id
syn keyword coreCifDictionary	_valence_ref_reference

" }}}1

hi def link cifBlock	Identifier
hi def link cifComment	Comment
hi def link cifSpecial	Special
hi def link cifString	String
hi def link coreCifDictionary	Identifier

let b:current_syntax = 'cif'
