" Language: crystallographic information file (chemical/x-cif)

if exists('b:current_syntax')
  finish
endif

let s:cpo_save = &cpo
set cpo&vim

syn case ignore

" https://it.iucr.org/Ga/ch2o2v0001/ {{{1
syn match cifComment /#.*/
syn match cifBlock /\<data_\S\+/
syn match cifBlock /\<save_\S\+/
syn match cifString /\(['"]\).\{-}\1/

syn keyword cifBlock loop_
syn keyword cifBlock stop_
syn keyword cifBlock global_

syn match cifSpecial /?/

" Core dictionary (coreCIF) version 2.4.5 definitions {{{1
" https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/index.html
" _atom_site_[]
syn keyword cif_coreCIF	_atom_site_adp_type
syn keyword cif_coreCIF	_atom_site_aniso_B_11
syn keyword cif_coreCIF	_atom_site_aniso_B_12
syn keyword cif_coreCIF	_atom_site_aniso_B_13
syn keyword cif_coreCIF	_atom_site_aniso_B_22
syn keyword cif_coreCIF	_atom_site_aniso_B_23
syn keyword cif_coreCIF	_atom_site_aniso_B_33
syn keyword cif_coreCIF	_atom_site_aniso_label
syn keyword cif_coreCIF	_atom_site_aniso_ratio
syn keyword cif_coreCIF	_atom_site_aniso_type_symbol
syn keyword cif_coreCIF	_atom_site_aniso_U_11
syn keyword cif_coreCIF	_atom_site_aniso_U_12
syn keyword cif_coreCIF	_atom_site_aniso_U_13
syn keyword cif_coreCIF	_atom_site_aniso_U_22
syn keyword cif_coreCIF	_atom_site_aniso_U_23
syn keyword cif_coreCIF	_atom_site_aniso_U_33
syn keyword cif_coreCIF	_atom_site_attached_hydrogens
syn keyword cif_coreCIF	_atom_site_B_equiv_geom_mean
syn keyword cif_coreCIF	_atom_site_B_iso_or_equiv
syn keyword cif_coreCIF	_atom_site_calc_attached_atom
syn keyword cif_coreCIF	_atom_site_calc_flag
syn keyword cif_coreCIF	_atom_site_Cartn_x
syn keyword cif_coreCIF	_atom_site_Cartn_y
syn keyword cif_coreCIF	_atom_site_Cartn_z
syn keyword cif_coreCIF	_atom_site_chemical_conn_number
syn keyword cif_coreCIF	_atom_site_constraints
syn keyword cif_coreCIF	_atom_site_description
syn keyword cif_coreCIF	_atom_site_disorder_assembly
syn keyword cif_coreCIF	_atom_site_disorder_group
syn keyword cif_coreCIF	_atom_site_fract_x
syn keyword cif_coreCIF	_atom_site_fract_y
syn keyword cif_coreCIF	_atom_site_fract_z
syn keyword cif_coreCIF	_atom_site_label
syn keyword cif_coreCIF	_atom_site_label_component_0
syn keyword cif_coreCIF	_atom_site_label_component_1
syn keyword cif_coreCIF	_atom_site_label_component_2
syn keyword cif_coreCIF	_atom_site_label_component_3
syn keyword cif_coreCIF	_atom_site_label_component_4
syn keyword cif_coreCIF	_atom_site_label_component_5
syn keyword cif_coreCIF	_atom_site_label_component_6
syn keyword cif_coreCIF	_atom_site_occupancy
syn keyword cif_coreCIFDeprecated	_atom_site_refinement_flags
syn keyword cif_coreCIF	_atom_site_refinement_flags_adp
syn keyword cif_coreCIF	_atom_site_refinement_flags_occupancy
syn keyword cif_coreCIF	_atom_site_refinement_flags_posn
syn keyword cif_coreCIF	_atom_site_restraints
syn keyword cif_coreCIF	_atom_site_site_symmetry_multiplicity
syn keyword cif_coreCIF	_atom_site_site_symmetry_order
syn keyword cifCcoreCifDeprecated	_atom_site_symmetry_multiplicity
syn keyword cif_coreCIFDeprecated	_atom_site_thermal_displace_type
syn keyword cif_coreCIF	_atom_site_type_symbol
syn keyword cif_coreCIF	_atom_site_U_equiv_geom_mean
syn keyword cif_coreCIF	_atom_site_U_iso_or_equiv
syn keyword cif_coreCIF	_atom_site_Wyckoff_symbol
" _atom_sites_[]
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_matrix_11
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_matrix_12
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_matrix_13
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_matrix_21
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_matrix_22
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_matrix_23
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_matrix_31
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_matrix_32
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_matrix_33
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_vector_1
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_vector_2
syn keyword cif_coreCIF	_atom_sites_Cartn_tran_vector_3
syn keyword cif_coreCIF	_atom_sites_Cartn_transform_axes
syn keyword cif_coreCIF	_atom_sites_fract_tran_matrix_11
syn keyword cif_coreCIF	_atom_sites_fract_tran_matrix_12
syn keyword cif_coreCIF	_atom_sites_fract_tran_matrix_13
syn keyword cif_coreCIF	_atom_sites_fract_tran_matrix_21
syn keyword cif_coreCIF	_atom_sites_fract_tran_matrix_22
syn keyword cif_coreCIF	_atom_sites_fract_tran_matrix_23
syn keyword cif_coreCIF	_atom_sites_fract_tran_matrix_31
syn keyword cif_coreCIF	_atom_sites_fract_tran_matrix_32
syn keyword cif_coreCIF	_atom_sites_fract_tran_matrix_33
syn keyword cif_coreCIF	_atom_sites_fract_tran_vector_1
syn keyword cif_coreCIF	_atom_sites_fract_tran_vector_2
syn keyword cif_coreCIF	_atom_sites_fract_tran_vector_3
syn keyword cif_coreCIF	_atom_sites_solution_primary
syn keyword cif_coreCIF	_atom_sites_solution_secondary
syn keyword cif_coreCIF	_atom_sites_solution_hydrogens
syn keyword cif_coreCIF	_atom_sites_special_details
" _atom_type_[]
syn match cif_coreCIF	/\<_atom_type_analytical_mass_%/
syn keyword cif_coreCIF	_atom_type_description
syn keyword cif_coreCIF	_atom_type_number_in_cell
syn keyword cif_coreCIF	_atom_type_oxidation_number
syn keyword cif_coreCIF	_atom_type_radius_bond
syn keyword cif_coreCIF	_atom_type_radius_contact
syn keyword cif_coreCIF	_atom_type_scat_Cromer_Mann_a1
syn keyword cif_coreCIF	_atom_type_scat_Cromer_Mann_a2
syn keyword cif_coreCIF	_atom_type_scat_Cromer_Mann_a3
syn keyword cif_coreCIF	_atom_type_scat_Cromer_Mann_a4
syn keyword cif_coreCIF	_atom_type_scat_Cromer_Mann_b1
syn keyword cif_coreCIF	_atom_type_scat_Cromer_Mann_b2
syn keyword cif_coreCIF	_atom_type_scat_Cromer_Mann_b3
syn keyword cif_coreCIF	_atom_type_scat_Cromer_Mann_b4
syn keyword cif_coreCIF	_atom_type_scat_Cromer_Mann_c
syn keyword cif_coreCIF	_atom_type_scat_dispersion_imag
syn keyword cif_coreCIF	_atom_type_scat_dispersion_real
syn keyword cif_coreCIF	_atom_type_scat_dispersion_source
syn keyword cif_coreCIF	_atom_type_scat_length_neutron
syn keyword cif_coreCIF	_atom_type_scat_source
syn keyword cif_coreCIF	_atom_type_scat_versus_stol_list
syn keyword cif_coreCIF	_atom_type_symbol
" _audit_[]
syn keyword cif_coreCIF	_audit_block_code
syn keyword cif_coreCIF	_audit_block_doi
syn keyword cif_coreCIF	_audit_creation_date
syn keyword cif_coreCIF	_audit_creation_method
syn keyword cif_coreCIF	_audit_update_record
" _audit_author_[]
syn keyword cif_coreCIF	_audit_author_address
syn keyword cif_coreCIF	_audit_author_name
" _audit_conform_[]
syn keyword cif_coreCIF	_audit_conform_dict_location
syn keyword cif_coreCIF	_audit_conform_dict_name
syn keyword cif_coreCIF	_audit_conform_dict_version
" _audit_contact_author_[]
syn keyword cif_coreCIF	_audit_contact_author_address
syn keyword cif_coreCIF	_audit_contact_author_email
syn keyword cif_coreCIF	_audit_contact_author_fax
syn keyword cif_coreCIF	_audit_contact_author_name
syn keyword cif_coreCIF	_audit_contact_author_phone
" _audit_link_[]
syn keyword cif_coreCIF	_audit_link_block_code
syn keyword cif_coreCIF	_audit_link_block_description
" _cell_[]
syn keyword cif_coreCIF	_cell_angle_alpha
syn keyword cif_coreCIF	_cell_angle_beta
syn keyword cif_coreCIF	_cell_angle_gamma
syn keyword cif_coreCIF	_cell_formula_units_Z
syn keyword cif_coreCIF	_cell_length_a
syn keyword cif_coreCIF	_cell_length_b
syn keyword cif_coreCIF	_cell_length_c
syn keyword cif_coreCIF	_cell_measurement_pressure
syn keyword cif_coreCIF	_cell_measurement_radiation
syn keyword cif_coreCIF	_cell_measurement_reflns_used
syn keyword cif_coreCIF	_cell_measurement_temperature
syn keyword cif_coreCIF	_cell_measurement_theta_max
syn keyword cif_coreCIF	_cell_measurement_theta_min
syn keyword cif_coreCIF	_cell_measurement_wavelength
syn keyword cif_coreCIF	_cell_reciprocal_angle_alpha
syn keyword cif_coreCIF	_cell_reciprocal_angle_beta
syn keyword cif_coreCIF	_cell_reciprocal_angle_gamma
syn keyword cif_coreCIF	_cell_reciprocal_length_a
syn keyword cif_coreCIF	_cell_reciprocal_length_b
syn keyword cif_coreCIF	_cell_reciprocal_length_c
syn keyword cif_coreCIF	_cell_special_details
syn keyword cif_coreCIF	_cell_volume
" _cell_measurement_refln_[]
syn keyword cif_coreCIF	_cell_measurement_refln_index_h
syn keyword cif_coreCIF	_cell_measurement_refln_index_k
syn keyword cif_coreCIF	_cell_measurement_refln_index_l
syn keyword cif_coreCIF	_cell_measurement_refln_theta
" _chemical_[]
syn keyword cif_coreCIF	_chemical_absolute_configuration
syn keyword cif_coreCIF	_chemical_compound_source
syn keyword cif_coreCIF	_chemical_enantioexcess_bulk
syn keyword cif_coreCIF	_chemical_enantioexcess_bulk_technique
syn keyword cif_coreCIF	_chemical_enantioexcess_crystal
syn keyword cif_coreCIF	_chemical_enantioexcess_crystal_technique
syn keyword cif_coreCIF	_chemical_identifier_inchi
syn keyword cif_coreCIF	_chemical_identifier_inchi_key
syn keyword cif_coreCIF	_chemical_identifier_inchi_version
syn keyword cif_coreCIF	_chemical_melting_point
syn keyword cif_coreCIF	_chemical_melting_point_gt
syn keyword cif_coreCIF	_chemical_melting_point_lt
syn keyword cif_coreCIF	_chemical_name_common
syn keyword cif_coreCIF	_chemical_name_mineral
syn keyword cif_coreCIF	_chemical_name_structure_type
syn keyword cif_coreCIF	_chemical_name_systematic
syn keyword cif_coreCIF	_chemical_optical_rotation
syn keyword cif_coreCIF	_chemical_properties_biological
syn keyword cif_coreCIF	_chemical_properties_physical
syn keyword cif_coreCIF	_chemical_temperature_decomposition
syn keyword cif_coreCIF	_chemical_temperature_decomposition_gt
syn keyword cif_coreCIF	_chemical_temperature_decomposition_lt
syn keyword cif_coreCIF	_chemical_temperature_sublimation
syn keyword cif_coreCIF	_chemical_temperature_sublimation_gt
syn keyword cif_coreCIF	_chemical_temperature_sublimation_lt
" _chemical_conn_atom_[]
syn keyword cif_coreCIF	_chemical_conn_atom_charge
syn keyword cif_coreCIF	_chemical_conn_atom_display_x
syn keyword cif_coreCIF	_chemical_conn_atom_display_y
syn keyword cif_coreCIF	_chemical_conn_atom_NCA
syn keyword cif_coreCIF	_chemical_conn_atom_NH
syn keyword cif_coreCIF	_chemical_conn_atom_number
syn keyword cif_coreCIF	_chemical_conn_atom_type_symbol
" _chemical_conn_bond_[]
syn keyword cif_coreCIF	_chemical_conn_bond_atom_1
syn keyword cif_coreCIF	_chemical_conn_bond_atom_2
syn keyword cif_coreCIF	_chemical_conn_bond_type
" _chemical_formula_[]
syn keyword cif_coreCIF	_chemical_formula_analytical
syn keyword cif_coreCIF	_chemical_formula_iupac
syn keyword cif_coreCIF	_chemical_formula_moiety
syn keyword cif_coreCIF	_chemical_formula_structural
syn keyword cif_coreCIF	_chemical_formula_sum
syn keyword cif_coreCIF	_chemical_formula_weight
syn keyword cif_coreCIF	_chemical_formula_weight_meas
" _citation_[]
syn keyword cif_coreCIF	_citation_abstract
syn keyword cif_coreCIF	_citation_abstract_id_CAS
syn keyword cif_coreCIF	_citation_book_id_ISBN
syn keyword cif_coreCIF	_citation_book_publisher
syn keyword cif_coreCIF	_citation_book_publisher_city
syn keyword cif_coreCIF	_citation_book_title
syn keyword cif_coreCIF	_citation_coordinate_linkage
syn keyword cif_coreCIF	_citation_country
syn keyword cif_coreCIF	_citation_database_id_CSD
syn keyword cif_coreCIF	_citation_database_id_Medline
syn keyword cif_coreCIF	_citation_doi
syn keyword cif_coreCIF	_citation_id
syn keyword cif_coreCIF	_citation_journal_abbrev
syn keyword cif_coreCIF	_citation_journal_full
syn keyword cif_coreCIF	_citation_journal_id_ASTM
syn keyword cif_coreCIF	_citation_journal_id_CSD
syn keyword cif_coreCIF	_citation_journal_id_ISSN
syn keyword cif_coreCIF	_citation_journal_issue
syn keyword cif_coreCIF	_citation_journal_volume
syn keyword cif_coreCIF	_citation_language
syn keyword cif_coreCIF	_citation_page_first
syn keyword cif_coreCIF	_citation_page_last
syn keyword cif_coreCIF	_citation_publisher
syn keyword cif_coreCIF	_citation_special_details
syn keyword cif_coreCIF	_citation_title
syn keyword cif_coreCIF	_citation_year
" _citation_author_[]
syn keyword cif_coreCIF	_citation_author_citation_id
syn keyword cif_coreCIF	_citation_author_name
syn keyword cif_coreCIF	_citation_author_ordinal
" _citation_editor_[]
syn keyword cif_coreCIF	_citation_editor_citation_id
syn keyword cif_coreCIF	_citation_editor_name
syn keyword cif_coreCIF	_citation_editor_ordinal
" _computing_[]
syn keyword cif_coreCIF	_computing_cell_refinement
syn keyword cif_coreCIF	_computing_data_collection
syn keyword cif_coreCIF	_computing_data_reduction
syn keyword cif_coreCIF	_computing_molecular_graphics
syn keyword cif_coreCIF	_computing_publication_material
syn keyword cif_coreCIF	_computing_structure_refinement
syn keyword cif_coreCIF	_computing_structure_solution
" _database_[]
syn keyword cif_coreCIF	_database_code_CAS
syn keyword cif_coreCIF	_database_code_COD
syn keyword cif_coreCIF	_database_code_CSD
syn keyword cif_coreCIF	_database_code_ICSD
syn keyword cif_coreCIF	_database_code_MDF
syn keyword cif_coreCIF	_database_code_NBS
syn keyword cif_coreCIF	_database_code_PDB
syn keyword cif_coreCIF	_database_code_PDF
syn keyword cif_coreCIF	_database_code_depnum_ccdc_archive
syn keyword cif_coreCIF	_database_code_depnum_ccdc_fiz
syn keyword cif_coreCIF	_database_code_depnum_ccdc_journal
syn keyword cif_coreCIF	_database_CSD_history
syn keyword cif_coreCIF	_database_dataset_doi
syn keyword cif_coreCIF	_database_journal_ASTM
syn keyword cif_coreCIF	_database_journal_CSD
" _diffrn_[]
syn keyword cif_coreCIF	_diffrn_ambient_environment
syn keyword cif_coreCIF	_diffrn_ambient_pressure
syn keyword cif_coreCIF	_diffrn_ambient_pressure_gt
syn keyword cif_coreCIF	_diffrn_ambient_pressure_lt
syn keyword cif_coreCIF	_diffrn_ambient_temperature
syn keyword cif_coreCIF	_diffrn_ambient_temperature_gt
syn keyword cif_coreCIF	_diffrn_ambient_temperature_lt
syn keyword cif_coreCIF	_diffrn_crystal_treatment
syn keyword cif_coreCIF	_diffrn_measured_fraction_theta_full
syn keyword cif_coreCIF	_diffrn_measured_fraction_theta_max
syn keyword cif_coreCIF	_diffrn_special_details
syn keyword cif_coreCIF	_diffrn_symmetry_description
" _diffrn_attenuator_[]
syn keyword cif_coreCIF	_diffrn_attenuator_code
syn keyword cif_coreCIF	_diffrn_attenuator_material
syn keyword cif_coreCIF	_diffrn_attenuator_scale
" _diffrn_detector_[]
syn keyword cif_coreCIF	_diffrn_detector
syn keyword cif_coreCIF	_diffrn_detector_area_resol_mean
syn keyword cif_coreCIF	_diffrn_detector_details
syn keyword cif_coreCIF	_diffrn_detector_dtime
syn keyword cif_coreCIF	_diffrn_detector_type
syn keyword cif_coreCIFDeprecated	_diffrn_radiation_detector
syn keyword cif_coreCIFDeprecated	_diffrn_radiation_detector_dtime
" _diffrn_measurement_[]
syn keyword cif_coreCIF	_diffrn_measurement_details
syn keyword cif_coreCIF	_diffrn_measurement_device
syn keyword cif_coreCIF	_diffrn_measurement_device_details
syn keyword cif_coreCIF	_diffrn_measurement_device_type
syn keyword cif_coreCIF	_diffrn_measurement_method
syn keyword cif_coreCIF	_diffrn_measurement_specimen_support
" _diffrn_orient_matrix_[]
syn keyword cif_coreCIF	_diffrn_orient_matrix_type
syn keyword cif_coreCIF	_diffrn_orient_matrix_UB_11
syn keyword cif_coreCIF	_diffrn_orient_matrix_UB_12
syn keyword cif_coreCIF	_diffrn_orient_matrix_UB_13
syn keyword cif_coreCIF	_diffrn_orient_matrix_UB_21
syn keyword cif_coreCIF	_diffrn_orient_matrix_UB_22
syn keyword cif_coreCIF	_diffrn_orient_matrix_UB_23
syn keyword cif_coreCIF	_diffrn_orient_matrix_UB_31
syn keyword cif_coreCIF	_diffrn_orient_matrix_UB_32
syn keyword cif_coreCIF	_diffrn_orient_matrix_UB_33
" _diffrn_orient_refln_[]
syn keyword cif_coreCIF	_diffrn_orient_refln_angle_chi
syn keyword cif_coreCIF	_diffrn_orient_refln_angle_kappa
syn keyword cif_coreCIF	_diffrn_orient_refln_angle_omega
syn keyword cif_coreCIF	_diffrn_orient_refln_angle_phi
syn keyword cif_coreCIF	_diffrn_orient_refln_angle_psi
syn keyword cif_coreCIF	_diffrn_orient_refln_angle_theta
syn keyword cif_coreCIF	_diffrn_orient_refln_index_h
syn keyword cif_coreCIF	_diffrn_orient_refln_index_k
syn keyword cif_coreCIF	_diffrn_orient_refln_index_l
" _diffrn_radiation_[]
syn keyword cif_coreCIF	_diffrn_radiation_collimation
syn keyword cif_coreCIF	_diffrn_radiation_filter_edge
syn keyword cif_coreCIF	_diffrn_radiation_inhomogeneity
syn keyword cif_coreCIF	_diffrn_radiation_monochromator
syn keyword cif_coreCIF	_diffrn_radiation_polarisn_norm
syn keyword cif_coreCIF	_diffrn_radiation_polarisn_ratio
syn keyword cif_coreCIF	_diffrn_radiation_probe
syn keyword cif_coreCIF	_diffrn_radiation_type
syn keyword cif_coreCIF	_diffrn_radiation_xray_symbol
" _diffrn_radiation_wavelength_[]
syn keyword cif_coreCIF	_diffrn_radiation_wavelength
syn keyword cif_coreCIF	_diffrn_radiation_wavelength_details
syn keyword cif_coreCIF	_diffrn_radiation_wavelength_determination
syn keyword cif_coreCIF	_diffrn_radiation_wavelength_id
syn keyword cif_coreCIF	_diffrn_radiation_wavelength_wt
" _diffrn_refln_[]
syn keyword cif_coreCIF	_diffrn_refln_angle_chi
syn keyword cif_coreCIF	_diffrn_refln_angle_kappa
syn keyword cif_coreCIF	_diffrn_refln_angle_omega
syn keyword cif_coreCIF	_diffrn_refln_angle_phi
syn keyword cif_coreCIF	_diffrn_refln_angle_psi
syn keyword cif_coreCIF	_diffrn_refln_angle_theta
syn keyword cif_coreCIF	_diffrn_refln_attenuator_code
syn keyword cif_coreCIF	_diffrn_refln_class_code
syn keyword cif_coreCIF	_diffrn_refln_counts_bg_1
syn keyword cif_coreCIF	_diffrn_refln_counts_bg_2
syn keyword cif_coreCIF	_diffrn_refln_counts_net
syn keyword cif_coreCIF	_diffrn_refln_counts_peak
syn keyword cif_coreCIF	_diffrn_refln_counts_total
syn keyword cif_coreCIF	_diffrn_refln_crystal_id
syn keyword cif_coreCIF	_diffrn_refln_detect_slit_horiz
syn keyword cif_coreCIF	_diffrn_refln_detect_slit_vert
syn keyword cif_coreCIF	_diffrn_refln_elapsed_time
syn keyword cif_coreCIF	_diffrn_refln_index_h
syn keyword cif_coreCIF	_diffrn_refln_index_k
syn keyword cif_coreCIF	_diffrn_refln_index_l
syn keyword cif_coreCIF	_diffrn_refln_intensity_net
syn keyword cif_coreCIFDeprecated	_diffrn_refln_intensity_sigma
syn keyword cif_coreCIF	_diffrn_refln_intensity_u
syn keyword cif_coreCIF	_diffrn_refln_scale_group_code
syn keyword cif_coreCIF	_diffrn_refln_scan_mode
syn keyword cif_coreCIF	_diffrn_refln_scan_mode_backgd
syn keyword cif_coreCIF	_diffrn_refln_scan_rate
syn keyword cif_coreCIF	_diffrn_refln_scan_time_backgd
syn keyword cif_coreCIF	_diffrn_refln_scan_width
syn match cif_coreCIF	/\<_diffrn_refln_sint\/lambda\>/
syn keyword cif_coreCIF	_diffrn_refln_standard_code
syn keyword cif_coreCIF	_diffrn_refln_wavelength
syn keyword cif_coreCIF	_diffrn_refln_wavelength_id
" _diffrn_reflns_[]
syn keyword cif_coreCIF	_diffrn_reflns_av_R_equivalents
syn match cif_coreCIFDeprecated	/\<_diffrn_reflns_av_sigmaI\/netI\>/
syn match cif_coreCIF	/\<_diffrn_reflns_av_unetI\/netI\>/
syn keyword cif_coreCIF	_diffrn_reflns_Laue_measured_fraction_full
syn keyword cif_coreCIF	_diffrn_reflns_Laue_measured_fraction_max
syn keyword cif_coreCIF	_diffrn_reflns_limit_h_max
syn keyword cif_coreCIF	_diffrn_reflns_limit_h_min
syn keyword cif_coreCIF	_diffrn_reflns_limit_k_max
syn keyword cif_coreCIF	_diffrn_reflns_limit_k_min
syn keyword cif_coreCIF	_diffrn_reflns_limit_l_max
syn keyword cif_coreCIF	_diffrn_reflns_limit_l_min
syn keyword cif_coreCIF	_diffrn_reflns_number
syn keyword cif_coreCIF	_diffrn_reflns_point_group_measured_fraction_full
syn keyword cif_coreCIF	_diffrn_reflns_point_group_measured_fraction_max
syn keyword cif_coreCIF	_diffrn_reflns_reduction_process
syn keyword cif_coreCIF	_diffrn_reflns_resolution_full
syn keyword cif_coreCIF	_diffrn_reflns_resolution_max
syn keyword cif_coreCIF	_diffrn_reflns_theta_full
syn keyword cif_coreCIF	_diffrn_reflns_theta_max
syn keyword cif_coreCIF	_diffrn_reflns_theta_min
syn keyword cif_coreCIF	_diffrn_reflns_transf_matrix_11
syn keyword cif_coreCIF	_diffrn_reflns_transf_matrix_12
syn keyword cif_coreCIF	_diffrn_reflns_transf_matrix_13
syn keyword cif_coreCIF	_diffrn_reflns_transf_matrix_21
syn keyword cif_coreCIF	_diffrn_reflns_transf_matrix_22
syn keyword cif_coreCIF	_diffrn_reflns_transf_matrix_23
syn keyword cif_coreCIF	_diffrn_reflns_transf_matrix_31
syn keyword cif_coreCIF	_diffrn_reflns_transf_matrix_32
syn keyword cif_coreCIF	_diffrn_reflns_transf_matrix_33
" _diffrn_reflns_class_[]
syn keyword cif_coreCIF	_diffrn_reflns_class_av_R_eq
syn match cif_coreCIFDeprecated	/\<_diffrn_reflns_class_av_sgI\/I\>/
syn match cif_coreCIF	/\<_diffrn_reflns_class_av_uI\/I\>/
syn keyword cif_coreCIF	_diffrn_reflns_class_code
syn keyword cif_coreCIF	_diffrn_reflns_class_d_res_high
syn keyword cif_coreCIF	_diffrn_reflns_class_d_res_low
syn keyword cif_coreCIF	_diffrn_reflns_class_description
syn keyword cif_coreCIF	_diffrn_reflns_class_number
" _diffrn_scale_group_[]
syn keyword cif_coreCIF	_diffrn_scale_group_code
syn keyword cif_coreCIF	_diffrn_scale_group_I_net
" _diffrn_source_[]
syn keyword cif_coreCIFDeprecated	_diffrn_radiation_source
syn keyword cif_coreCIF	_diffrn_source
syn keyword cif_coreCIF	_diffrn_source_current
syn keyword cif_coreCIF	_diffrn_source_details
syn keyword cif_coreCIF	_diffrn_source_power
syn keyword cif_coreCIF	_diffrn_source_size
syn match cif_coreCIF	/\<_diffrn_source_take-off_angle\>/
syn keyword cif_coreCIF	_diffrn_source_target
syn keyword cif_coreCIF	_diffrn_source_type
syn keyword cif_coreCIF	_diffrn_source_voltage
" _diffrn_standard_refln_[]
syn keyword cif_coreCIF	_diffrn_standard_refln_code
syn keyword cif_coreCIF	_diffrn_standard_refln_index_h
syn keyword cif_coreCIF	_diffrn_standard_refln_index_k
syn keyword cif_coreCIF	_diffrn_standard_refln_index_l
" _diffrn_standards_[]
syn match cif_coreCIF	/\<_diffrn_standards_decay_%/
syn keyword cif_coreCIF	_diffrn_standards_interval_count
syn keyword cif_coreCIF	_diffrn_standards_interval_time
syn keyword cif_coreCIF	_diffrn_standards_number
syn keyword cif_coreCIFDeprecated	_diffrn_standards_scale_sigma
syn keyword cif_coreCIF	_diffrn_standards_scale_u
" _exptl_[]
syn keyword cif_coreCIF	_exptl_absorpt_coefficient_mu
syn keyword cif_coreCIF	_exptl_absorpt_correction_T_max
syn keyword cif_coreCIF	_exptl_absorpt_correction_T_min
syn keyword cif_coreCIF	_exptl_absorpt_correction_type
syn keyword cif_coreCIF	_exptl_absorpt_process_details
syn keyword cif_coreCIF	_exptl_crystals_number
syn keyword cif_coreCIF	_exptl_special_details
syn keyword cif_coreCIF	_exptl_transmission_factor_max
syn keyword cif_coreCIF	_exptl_transmission_factor_min
" _exptl_crystal_[]
syn keyword cif_coreCIF	_exptl_crystal_colour
syn keyword cif_coreCIF	_exptl_crystal_colour_lustre
syn keyword cif_coreCIF	_exptl_crystal_colour_modifier
syn keyword cif_coreCIF	_exptl_crystal_colour_primary
syn keyword cif_coreCIF	_exptl_crystal_density_diffrn
syn keyword cif_coreCIF	_exptl_crystal_density_meas
syn keyword cif_coreCIF	_exptl_crystal_density_meas_gt
syn keyword cif_coreCIF	_exptl_crystal_density_meas_lt
syn keyword cif_coreCIF	_exptl_crystal_density_meas_temp
syn keyword cif_coreCIF	_exptl_crystal_density_meas_temp_gt
syn keyword cif_coreCIF	_exptl_crystal_density_meas_temp_lt
syn keyword cif_coreCIF	_exptl_crystal_density_method
syn keyword cif_coreCIF	_exptl_crystal_description
syn keyword cif_coreCIF	_exptl_crystal_F_000
syn keyword cif_coreCIF	_exptl_crystal_id
syn keyword cif_coreCIF	_exptl_crystal_preparation
syn keyword cif_coreCIF	_exptl_crystal_pressure_history
syn keyword cif_coreCIF	_exptl_crystal_recrystallization_method
syn keyword cif_coreCIF	_exptl_crystal_size_length
syn keyword cif_coreCIF	_exptl_crystal_size_max
syn keyword cif_coreCIF	_exptl_crystal_size_mid
syn keyword cif_coreCIF	_exptl_crystal_size_min
syn keyword cif_coreCIF	_exptl_crystal_size_rad
syn keyword cif_coreCIF	_exptl_crystal_thermal_history
" _exptl_crystal_face_[]
syn keyword cif_coreCIF	_exptl_crystal_face_diffr_chi
syn keyword cif_coreCIF	_exptl_crystal_face_diffr_kappa
syn keyword cif_coreCIF	_exptl_crystal_face_diffr_phi
syn keyword cif_coreCIF	_exptl_crystal_face_diffr_psi
syn keyword cif_coreCIF	_exptl_crystal_face_index_h
syn keyword cif_coreCIF	_exptl_crystal_face_index_k
syn keyword cif_coreCIF	_exptl_crystal_face_index_l
syn keyword cif_coreCIF	_exptl_crystal_face_perp_dist
" _geom_[]
syn keyword cif_coreCIF	_geom_special_details
" _geom_angle_[]
syn keyword cif_coreCIF	_geom_angle
syn keyword cif_coreCIF	_geom_angle_atom_site_label_1
syn keyword cif_coreCIF	_geom_angle_atom_site_label_2
syn keyword cif_coreCIF	_geom_angle_atom_site_label_3
syn keyword cif_coreCIF	_geom_angle_publ_flag
syn keyword cif_coreCIF	_geom_angle_site_symmetry_1
syn keyword cif_coreCIF	_geom_angle_site_symmetry_2
syn keyword cif_coreCIF	_geom_angle_site_symmetry_3
" _geom_bond_[]
syn keyword cif_coreCIF	_geom_bond_atom_site_label_1
syn keyword cif_coreCIF	_geom_bond_atom_site_label_2
syn keyword cif_coreCIF	_geom_bond_distance
syn keyword cif_coreCIF	_geom_bond_multiplicity
syn keyword cif_coreCIF	_geom_bond_publ_flag
syn keyword cif_coreCIF	_geom_bond_site_symmetry_1
syn keyword cif_coreCIF	_geom_bond_site_symmetry_2
syn keyword cif_coreCIF	_geom_bond_valence
" _geom_contact_[]
syn keyword cif_coreCIF	_geom_contact_atom_site_label_1
syn keyword cif_coreCIF	_geom_contact_atom_site_label_2
syn keyword cif_coreCIF	_geom_contact_distance
syn keyword cif_coreCIF	_geom_contact_publ_flag
syn keyword cif_coreCIF	_geom_contact_site_symmetry_1
syn keyword cif_coreCIF	_geom_contact_site_symmetry_2
" _geom_hbond_[]
syn keyword cif_coreCIF	_geom_hbond_angle_DHA
syn keyword cif_coreCIF	_geom_hbond_atom_site_label_D
syn keyword cif_coreCIF	_geom_hbond_atom_site_label_H
syn keyword cif_coreCIF	_geom_hbond_atom_site_label_A
syn keyword cif_coreCIF	_geom_hbond_distance_DH
syn keyword cif_coreCIF	_geom_hbond_distance_HA
syn keyword cif_coreCIF	_geom_hbond_distance_DA
syn keyword cif_coreCIF	_geom_hbond_publ_flag
syn keyword cif_coreCIF	_geom_hbond_site_symmetry_D
syn keyword cif_coreCIF	_geom_hbond_site_symmetry_H
syn keyword cif_coreCIF	_geom_hbond_site_symmetry_A
" _geom_torsion_[]
syn keyword cif_coreCIF	_geom_torsion
syn keyword cif_coreCIF	_geom_torsion_atom_site_label_1
syn keyword cif_coreCIF	_geom_torsion_atom_site_label_2
syn keyword cif_coreCIF	_geom_torsion_atom_site_label_3
syn keyword cif_coreCIF	_geom_torsion_atom_site_label_4
syn keyword cif_coreCIF	_geom_torsion_publ_flag
syn keyword cif_coreCIF	_geom_torsion_site_symmetry_1
syn keyword cif_coreCIF	_geom_torsion_site_symmetry_2
syn keyword cif_coreCIF	_geom_torsion_site_symmetry_3
syn keyword cif_coreCIF	_geom_torsion_site_symmetry_4
" _journal_[]
syn keyword cif_coreCIF	_journal_coden_ASTM
syn keyword cif_coreCIF	_journal_coden_Cambridge
syn keyword cif_coreCIF	_journal_coeditor_address
syn keyword cif_coreCIF	_journal_coeditor_code
syn keyword cif_coreCIF	_journal_coeditor_email
syn keyword cif_coreCIF	_journal_coeditor_fax
syn keyword cif_coreCIF	_journal_coeditor_name
syn keyword cif_coreCIF	_journal_coeditor_notes
syn keyword cif_coreCIF	_journal_coeditor_phone
syn keyword cif_coreCIF	_journal_data_validation_number
syn keyword cif_coreCIF	_journal_date_accepted
syn keyword cif_coreCIF	_journal_date_from_coeditor
syn keyword cif_coreCIF	_journal_date_to_coeditor
syn keyword cif_coreCIF	_journal_date_printers_final
syn keyword cif_coreCIF	_journal_date_printers_first
syn keyword cif_coreCIF	_journal_date_proofs_in
syn keyword cif_coreCIF	_journal_date_proofs_out
syn keyword cif_coreCIF	_journal_date_recd_copyright
syn keyword cif_coreCIF	_journal_date_recd_electronic
syn keyword cif_coreCIF	_journal_date_recd_hard_copy
syn keyword cif_coreCIF	_journal_issue
syn keyword cif_coreCIF	_journal_language
syn keyword cif_coreCIF	_journal_name_full
syn keyword cif_coreCIF	_journal_page_first
syn keyword cif_coreCIF	_journal_page_last
syn keyword cif_coreCIF	_journal_paper_category
syn keyword cif_coreCIF	_journal_paper_doi
syn keyword cif_coreCIF	_journal_suppl_publ_number
syn keyword cif_coreCIF	_journal_suppl_publ_pages
syn keyword cif_coreCIF	_journal_techeditor_address
syn keyword cif_coreCIF	_journal_techeditor_code
syn keyword cif_coreCIF	_journal_techeditor_email
syn keyword cif_coreCIF	_journal_techeditor_fax
syn keyword cif_coreCIF	_journal_techeditor_name
syn keyword cif_coreCIF	_journal_techeditor_notes
syn keyword cif_coreCIF	_journal_techeditor_phone
syn keyword cif_coreCIF	_journal_volume
syn keyword cif_coreCIF	_journal_year
" _journal_index_[]
syn keyword cif_coreCIF	_journal_index_subterm
syn keyword cif_coreCIF	_journal_index_term
syn keyword cif_coreCIF	_journal_index_type
" _publ_[]
syn keyword cif_coreCIF	_publ_contact_author
syn keyword cif_coreCIF	_publ_contact_author_address
syn keyword cif_coreCIF	_publ_contact_author_email
syn keyword cif_coreCIF	_publ_contact_author_fax
syn keyword cif_coreCIF	_publ_contact_author_id_iucr
syn keyword cif_coreCIF	_publ_contact_author_id_orcid
syn keyword cif_coreCIF	_publ_contact_author_name
syn keyword cif_coreCIF	_publ_contact_author_phone
syn keyword cif_coreCIF	_publ_contact_letter
syn keyword cif_coreCIF	_publ_manuscript_creation
syn keyword cif_coreCIF	_publ_manuscript_processed
syn keyword cif_coreCIF	_publ_manuscript_text
syn keyword cif_coreCIF	_publ_requested_category
syn keyword cif_coreCIF	_publ_requested_coeditor_name
syn keyword cif_coreCIF	_publ_requested_journal
syn keyword cif_coreCIF	_publ_section_title
syn keyword cif_coreCIF	_publ_section_title_footnote
syn keyword cif_coreCIF	_publ_section_synopsis
syn keyword cif_coreCIF	_publ_section_abstract
syn keyword cif_coreCIF	_publ_section_comment
syn keyword cif_coreCIF	_publ_section_introduction
syn keyword cif_coreCIF	_publ_section_experimental
syn keyword cif_coreCIF	_publ_section_exptl_prep
syn keyword cif_coreCIF	_publ_section_exptl_refinement
syn keyword cif_coreCIF	_publ_section_exptl_solution
syn keyword cif_coreCIF	_publ_section_discussion
syn keyword cif_coreCIF	_publ_section_acknowledgements
syn keyword cif_coreCIF	_publ_section_references
syn keyword cif_coreCIF	_publ_section_related_literature
syn keyword cif_coreCIF	_publ_section_figure_captions
syn keyword cif_coreCIF	_publ_section_table_legends
syn keyword cif_coreCIF	_publ_section_keywords
" _publ_author_[]
syn keyword cif_coreCIF	_publ_author_address
syn keyword cif_coreCIF	_publ_author_email
syn keyword cif_coreCIF	_publ_author_footnote
syn keyword cif_coreCIF	_publ_author_id_iucr
syn keyword cif_coreCIF	_publ_author_id_orcid
syn keyword cif_coreCIF	_publ_author_name
" _publ_body_[]
syn keyword cif_coreCIF	_publ_body_contents
syn keyword cif_coreCIF	_publ_body_element
syn keyword cif_coreCIF	_publ_body_format
syn keyword cif_coreCIF	_publ_body_label
syn keyword cif_coreCIF	_publ_body_title
" _publ_manuscript_incl_[]
syn keyword cif_coreCIF	_publ_manuscript_incl_extra_defn
syn keyword cif_coreCIF	_publ_manuscript_incl_extra_info
syn keyword cif_coreCIF	_publ_manuscript_incl_extra_item
" _refine_[]
syn keyword cif_coreCIF	_refine_diff_density_max
syn keyword cif_coreCIF	_refine_diff_density_min
syn keyword cif_coreCIF	_refine_diff_density_rms
syn keyword cif_coreCIF	_refine_ls_abs_structure_details
syn keyword cif_coreCIF	_refine_ls_abs_structure_Flack
syn keyword cif_coreCIF	_refine_ls_abs_structure_Rogers
syn keyword cif_coreCIF	_refine_ls_d_res_high
syn keyword cif_coreCIF	_refine_ls_d_res_low
syn keyword cif_coreCIF	_refine_ls_extinction_coef
syn keyword cif_coreCIF	_refine_ls_extinction_expression
syn keyword cif_coreCIF	_refine_ls_extinction_method
syn keyword cif_coreCIF	_refine_ls_F_calc_details
syn keyword cif_coreCIF	_refine_ls_F_calc_formula
syn keyword cif_coreCIF	_refine_ls_F_calc_precision
syn keyword cif_coreCIF	_refine_ls_goodness_of_fit_all
syn keyword cif_coreCIF	_refine_ls_goodness_of_fit_gt
syn keyword cif_coreCIFDeprecated	_refine_ls_goodness_of_fit_obs
syn keyword cif_coreCIF	_refine_ls_goodness_of_fit_ref
syn keyword cif_coreCIF	_refine_ls_hydrogen_treatment
syn keyword cif_coreCIF	_refine_ls_matrix_type
syn keyword cif_coreCIF	_refine_ls_number_constraints
syn keyword cif_coreCIF	_refine_ls_number_parameters
syn keyword cif_coreCIF	_refine_ls_number_reflns
syn keyword cif_coreCIF	_refine_ls_number_restraints
syn keyword cif_coreCIF	_refine_ls_R_factor_all
syn keyword cif_coreCIF	_refine_ls_R_factor_gt
syn keyword cif_coreCIFDeprecated	_refine_ls_R_factor_obs
syn keyword cif_coreCIF	_refine_ls_R_Fsqd_factor
syn keyword cif_coreCIF	_refine_ls_R_I_factor
syn keyword cif_coreCIF	_refine_ls_restrained_S_all
syn keyword cif_coreCIF	_refine_ls_restrained_S_gt
syn keyword cif_coreCIFDeprecated	_refine_ls_restrained_S_obs
syn match cif_coreCIFDeprecated	/\<_refine_ls_shift\/esd_max\>/
syn match cif_coreCIFDeprecated	/\<_refine_ls_shift\/esd_mean\>/
syn match cif_coreCIF	/\<_refine_ls_shift\/su_max\>/
syn match cif_coreCIF	/\<_refine_ls_shift\/su_max_lt\>/
syn match cif_coreCIF	/\<_refine_ls_shift\/su_mean\>/
syn match cif_coreCIF	/\<_refine_ls_shift\/su_mean_lt\>/
syn keyword cif_coreCIF	_refine_ls_structure_factor_coef
syn keyword cif_coreCIF	_refine_ls_weighting_details
syn keyword cif_coreCIF	_refine_ls_weighting_scheme
syn keyword cif_coreCIF	_refine_ls_wR_factor_all
syn keyword cif_coreCIF	_refine_ls_wR_factor_gt
syn keyword cif_coreCIFDeprecated	_refine_ls_wR_factor_obs
syn keyword cif_coreCIF	_refine_ls_wR_factor_ref
syn keyword cif_coreCIF	_refine_special_details
" _refine_ls_class_[]
syn keyword cif_coreCIF	_refine_ls_class_code
syn keyword cif_coreCIF	_refine_ls_class_d_res_high
syn keyword cif_coreCIF	_refine_ls_class_d_res_low
syn keyword cif_coreCIF	_refine_ls_class_R_factor_all
syn keyword cif_coreCIF	_refine_ls_class_R_factor_gt
syn keyword cif_coreCIF	_refine_ls_class_R_Fsqd_factor
syn keyword cif_coreCIF	_refine_ls_class_R_I_factor
syn keyword cif_coreCIF	_refine_ls_class_wR_factor_all
" _refln_[]
syn keyword cif_coreCIF	_refln_A_calc
syn keyword cif_coreCIF	_refln_A_meas
syn keyword cif_coreCIF	_refln_B_calc
syn keyword cif_coreCIF	_refln_B_meas
syn keyword cif_coreCIF	_refln_class_code
syn keyword cif_coreCIF	_refln_crystal_id
syn keyword cif_coreCIF	_refln_d_spacing
syn keyword cif_coreCIF	_refln_F_calc
syn keyword cif_coreCIF	_refln_F_meas
syn keyword cif_coreCIF	_refln_F_sigma
syn keyword cif_coreCIF	_refln_F_squared_calc
syn keyword cif_coreCIF	_refln_F_squared_meas
syn keyword cif_coreCIF	_refln_F_squared_sigma
syn keyword cif_coreCIF	_refln_include_status
syn keyword cif_coreCIF	_refln_index_h
syn keyword cif_coreCIF	_refln_index_k
syn keyword cif_coreCIF	_refln_index_l
syn keyword cif_coreCIF	_refln_intensity_calc
syn keyword cif_coreCIF	_refln_intensity_meas
syn keyword cif_coreCIF	_refln_intensity_sigma
syn keyword cif_coreCIF	_refln_mean_path_length_tbar
syn keyword cif_coreCIFDeprecated	_refln_observed_status
syn keyword cif_coreCIF	_refln_phase_calc
syn keyword cif_coreCIF	_refln_phase_meas
syn keyword cif_coreCIF	_refln_refinement_status
syn keyword cif_coreCIF	_refln_scale_group_code
syn match cif_coreCIF	/\<_refln_sint\/lambda\>/
syn keyword cif_coreCIF	_refln_symmetry_epsilon
syn keyword cif_coreCIF	_refln_symmetry_multiplicity
syn keyword cif_coreCIF	_refln_wavelength
syn keyword cif_coreCIF	_refln_wavelength_id
" _reflns_[]
syn keyword cif_coreCIF	_reflns_d_resolution_high
syn keyword cif_coreCIF	_reflns_d_resolution_low
syn keyword cif_coreCIF	_reflns_Friedel_coverage
syn keyword cif_coreCIF	_reflns_Friedel_fraction_full
syn keyword cif_coreCIF	_reflns_Friedel_fraction_max
syn keyword cif_coreCIF	_reflns_limit_h_max
syn keyword cif_coreCIF	_reflns_limit_h_min
syn keyword cif_coreCIF	_reflns_limit_k_max
syn keyword cif_coreCIF	_reflns_limit_k_min
syn keyword cif_coreCIF	_reflns_limit_l_max
syn keyword cif_coreCIF	_reflns_limit_l_min
syn keyword cif_coreCIF	_reflns_number_gt
syn keyword cif_coreCIFDeprecated	_reflns_number_observed
syn keyword cif_coreCIF	_reflns_number_total
syn keyword cif_coreCIFDeprecated	_reflns_observed_criterion
syn keyword cif_coreCIF	_reflns_special_details
syn keyword cif_coreCIF	_reflns_threshold_expression
" _reflns_class_[]
syn keyword cif_coreCIF	_reflns_class_code
syn keyword cif_coreCIF	_reflns_class_d_res_high
syn keyword cif_coreCIF	_reflns_class_d_res_low
syn keyword cif_coreCIF	_reflns_class_description
syn keyword cif_coreCIF	_reflns_class_number_gt
syn keyword cif_coreCIF	_reflns_class_number_total
syn keyword cif_coreCIF	_reflns_class_R_factor_all
syn keyword cif_coreCIF	_reflns_class_R_factor_gt
syn keyword cif_coreCIF	_reflns_class_R_Fsqd_factor
syn keyword cif_coreCIF	_reflns_class_R_I_factor
syn keyword cif_coreCIF	_reflns_class_wR_factor_all
" _reflns_scale_[]
syn keyword cif_coreCIF	_reflns_scale_group_code
syn keyword cif_coreCIF	_reflns_scale_meas_F
syn keyword cif_coreCIF	_reflns_scale_meas_F_squared
syn keyword cif_coreCIF	_reflns_scale_meas_intensity
" _reflns_shell_[]
syn keyword cif_coreCIF	_reflns_shell_d_res_high
syn keyword cif_coreCIF	_reflns_shell_d_res_low
syn keyword cif_coreCIFDeprecated	_reflns_shell_meanI_over_sigI_all
syn keyword cif_coreCIFDeprecated	_reflns_shell_meanI_over_sigI_gt
syn keyword cif_coreCIFDeprecated	_reflns_shell_meanI_over_sigI_obs
syn keyword cif_coreCIF	_reflns_shell_meanI_over_uI_all
syn keyword cif_coreCIF	_reflns_shell_meanI_over_uI_gt
syn keyword cif_coreCIF	_reflns_shell_number_measured_all
syn keyword cif_coreCIF	_reflns_shell_number_measured_gt
syn keyword cif_coreCIFDeprecated	_reflns_shell_number_measured_obs
syn keyword cif_coreCIF	_reflns_shell_number_possible
syn keyword cif_coreCIF	_reflns_shell_number_unique_all
syn keyword cif_coreCIF	_reflns_shell_number_unique_gt
syn keyword cif_coreCIFDeprecated	_reflns_shell_number_unique_obs
syn keyword cif_coreCIF	_reflns_shell_percent_possible_all
syn keyword cif_coreCIF	_reflns_shell_percent_possible_gt
syn keyword cif_coreCIFDeprecated	_reflns_shell_percent_possible_obs
syn keyword cif_coreCIF	_reflns_shell_Rmerge_F_all
syn keyword cif_coreCIF	_reflns_shell_Rmerge_F_gt
syn keyword cif_coreCIFDeprecated	_reflns_shell_Rmerge_F_obs
syn keyword cif_coreCIF	_reflns_shell_Rmerge_I_all
syn keyword cif_coreCIF	_reflns_shell_Rmerge_I_gt
syn keyword cif_coreCIFDeprecated	_reflns_shell_Rmerge_I_obs
" _space_group_[]
syn keyword cif_coreCIF	_space_group_crystal_system
syn keyword cif_coreCIF	_space_group_id
syn keyword cif_coreCIF	_space_group_IT_number
syn match cif_coreCIF	/\<_space_group_name_H-M_alt\>/
syn keyword cif_coreCIF	_space_group_name_Hall
" _space_group_symop_[]
syn keyword cif_coreCIF	_space_group_symop_id
syn keyword cif_coreCIF	_space_group_symop_operation_xyz
syn keyword cif_coreCIF	_space_group_symop_sg_id
" _symmetry_[]
syn keyword cif_coreCIFDeprecated	_symmetry_cell_setting
syn keyword cif_coreCIFDeprecated	_symmetry_Int_Tables_number
syn match cif_coreCIFDeprecated	/\<_symmetry_space_group_name_H-M\>/
syn keyword cif_coreCIFDeprecated	_symmetry_space_group_name_Hall
" _symmetry_equiv_[]
syn keyword cif_coreCIFDeprecated	_symmetry_equiv_pos_as_xyz
syn keyword cif_coreCIFDeprecated	_symmetry_equiv_pos_site_id
" _valence_param_[]
syn keyword cif_coreCIF	_valence_param_atom_1
syn keyword cif_coreCIF	_valence_param_atom_1_valence
syn keyword cif_coreCIF	_valence_param_atom_2
syn keyword cif_coreCIF	_valence_param_atom_2_valence
syn keyword cif_coreCIF	_valence_param_B
syn keyword cif_coreCIF	_valence_param_details
syn keyword cif_coreCIF	_valence_param_id
syn keyword cif_coreCIF	_valence_param_ref_id
syn keyword cif_coreCIF	_valence_param_Ro
" _valence_ref_[]
syn keyword cif_coreCIF	_valence_ref_id
syn keyword cif_coreCIF	_valence_ref_reference

" Symmetry dictionary (symCIF) version 1.0.1 definitions {{{1
" https://www.iucr.org/__data/iucr/cifdic_html/2/cif_sym.dic/index.html
" _space_group.name_H-M_ref {{{2
syn match cif_symCIF_H_M	/'P 1'/		" 1
syn match cif_symCIF_H_M	/'P -1'/	" 2
syn match cif_symCIF_H_M	/'P 2'/		" 3
syn match cif_symCIF_H_M	/'P 21'/	" 4
syn match cif_symCIF_H_M	/'C 2'/		" 5
syn match cif_symCIF_H_M	/'P m'/		" 6
syn match cif_symCIF_H_M	/'P c'/		" 7
syn match cif_symCIF_H_M	/'C m'/		" 8
syn match cif_symCIF_H_M	/'C c'/		" 9
syn match cif_symCIF_H_M	/'P 2\/m'/	" 10
syn match cif_symCIF_H_M	/'P 21\/m'/	" 11
syn match cif_symCIF_H_M	/'C 2\/m'/	" 12
syn match cif_symCIF_H_M	/'P 2\/c'/	" 13
syn match cif_symCIF_H_M	/'P 21\/c'/	" 14
syn match cif_symCIF_H_M	/'C 2\/c'/	" 15
syn match cif_symCIF_H_M	/'P 2 2 2'/	" 16
syn match cif_symCIF_H_M	/'P 2 2 21'/	" 17
syn match cif_symCIF_H_M	/'P 21 21 2'/	" 18
syn match cif_symCIF_H_M	/'P 21 21 21'/	" 19
syn match cif_symCIF_H_M	/'C 2 2 21'/	" 20
syn match cif_symCIF_H_M	/'C 2 2 2'/	" 21
syn match cif_symCIF_H_M	/'F 2 2 2'/	" 22
syn match cif_symCIF_H_M	/'I 2 2 2'/	" 23
syn match cif_symCIF_H_M	/'I 21 21 21'/	" 24
syn match cif_symCIF_H_M	/'P m m 2'/	" 25
syn match cif_symCIF_H_M	/'P m c 21'/	" 26
syn match cif_symCIF_H_M	/'P c c 2'/	" 27
syn match cif_symCIF_H_M	/'P m a 2'/	" 28
syn match cif_symCIF_H_M	/'P c a 21'/	" 29
syn match cif_symCIF_H_M	/'P n c 2'/	" 30
syn match cif_symCIF_H_M	/'P m n 21'/	" 31
syn match cif_symCIF_H_M	/'P b a 2'/	" 32
syn match cif_symCIF_H_M	/'P n a 21'/	" 33
syn match cif_symCIF_H_M	/'P n n 2'/	" 34
syn match cif_symCIF_H_M	/'C m m 2'/	" 35
syn match cif_symCIF_H_M	/'C m c 21'/	" 36
syn match cif_symCIF_H_M	/'C c c 2'/	" 37
syn match cif_symCIF_H_M	/'A m m 2'/	" 38
syn match cif_symCIF_H_M	/'A e m 2'/	" 39
syn match cif_symCIF_H_M	/'A m a 2'/	" 40
syn match cif_symCIF_H_M	/'A e a 2'/	" 41
syn match cif_symCIF_H_M	/'F m m 2'/	" 42
syn match cif_symCIF_H_M	/'F d d 2'/	" 43
syn match cif_symCIF_H_M	/'I m m 2'/	" 44
syn match cif_symCIF_H_M	/'I b a 2'/	" 45
syn match cif_symCIF_H_M	/'I m a 2'/	" 46
syn match cif_symCIF_H_M	/'P m m m'/	" 47
syn match cif_symCIF_H_M	/'P n n n'/	" 48
syn match cif_symCIF_H_M	/'P c c m'/	" 49
syn match cif_symCIF_H_M	/'P b a n'/	" 50
syn match cif_symCIF_H_M	/'P m m a'/	" 51
syn match cif_symCIF_H_M	/'P n n a'/	" 52
syn match cif_symCIF_H_M	/'P m n a'/	" 53
syn match cif_symCIF_H_M	/'P c c a'/	" 54
syn match cif_symCIF_H_M	/'P b a m'/	" 55
syn match cif_symCIF_H_M	/'P c c n'/	" 56
syn match cif_symCIF_H_M	/'P b c m'/	" 57
syn match cif_symCIF_H_M	/'P n n m'/	" 58
syn match cif_symCIF_H_M	/'P m m n'/	" 59
syn match cif_symCIF_H_M	/'P b c n'/	" 60
syn match cif_symCIF_H_M	/'P b c a'/	" 61
syn match cif_symCIF_H_M	/'P n m a'/	" 62
syn match cif_symCIF_H_M	/'C m c m'/	" 63
syn match cif_symCIF_H_M	/'C m c e'/	" 64
syn match cif_symCIF_H_M	/'C m m m'/	" 65
syn match cif_symCIF_H_M	/'C c c m'/	" 66
syn match cif_symCIF_H_M	/'C m m e'/	" 67
syn match cif_symCIF_H_M	/'C c c e'/	" 68
syn match cif_symCIF_H_M	/'F m m m'/	" 69
syn match cif_symCIF_H_M	/'F d d d'/	" 70
syn match cif_symCIF_H_M	/'I m m m'/	" 71
syn match cif_symCIF_H_M	/'I b a m'/	" 72
syn match cif_symCIF_H_M	/'I b c a'/	" 73
syn match cif_symCIF_H_M	/'I m m a'/	" 74
syn match cif_symCIF_H_M	/'P 4'/		" 75
syn match cif_symCIF_H_M	/'P 41'/	" 76
syn match cif_symCIF_H_M	/'P 42'/	" 77
syn match cif_symCIF_H_M	/'P 43'/	" 78
syn match cif_symCIF_H_M	/'I 4'/		" 79
syn match cif_symCIF_H_M	/'I 41'/	" 80
syn match cif_symCIF_H_M	/'P -4'/	" 81
syn match cif_symCIF_H_M	/'I -4'/	" 82
syn match cif_symCIF_H_M	/'P 4\/m'/	" 83
syn match cif_symCIF_H_M	/'P 42\/m'/	" 84
syn match cif_symCIF_H_M	/'P 4\/n'/	" 85
syn match cif_symCIF_H_M	/'P 42\/n'/	" 86
syn match cif_symCIF_H_M	/'I 4\/m'/	" 87
syn match cif_symCIF_H_M	/'I 41\/a'/	" 88
syn match cif_symCIF_H_M	/'P 4 2 2'/	" 89
syn match cif_symCIF_H_M	/'P 4 21 2'/	" 90
syn match cif_symCIF_H_M	/'P 41 2 2'/	" 91
syn match cif_symCIF_H_M	/'P 41 21 2'/	" 92
syn match cif_symCIF_H_M	/'P 42 2 2'/	" 93
syn match cif_symCIF_H_M	/'P 42 21 2'/	" 94
syn match cif_symCIF_H_M	/'P 43 2 2'/	" 95
syn match cif_symCIF_H_M	/'P 43 21 2'/	" 96
syn match cif_symCIF_H_M	/'I 4 2 2'/	" 97
syn match cif_symCIF_H_M	/'I 41 2 2'/	" 98
syn match cif_symCIF_H_M	/'P 4 m m'/	" 99
syn match cif_symCIF_H_M	/'P 4 b m'/	" 100
syn match cif_symCIF_H_M	/'P 42 c m'/	" 101
syn match cif_symCIF_H_M	/'P 42 n m'/	" 102
syn match cif_symCIF_H_M	/'P 4 c c'/	" 103
syn match cif_symCIF_H_M	/'P 4 n c'/	" 104
syn match cif_symCIF_H_M	/'P 42 m c'/	" 105
syn match cif_symCIF_H_M	/'P 42 b c'/	" 106
syn match cif_symCIF_H_M	/'I 4 m m'/	" 107
syn match cif_symCIF_H_M	/'I 4 c m'/	" 108
syn match cif_symCIF_H_M	/'I 41 m d'/	" 109
syn match cif_symCIF_H_M	/'I 41 c d'/	" 110
syn match cif_symCIF_H_M	/'P -4 2 m'/	" 111
syn match cif_symCIF_H_M	/'P -4 2 c'/	" 112
syn match cif_symCIF_H_M	/'P -4 21 m'/	" 113
syn match cif_symCIF_H_M	/'P -4 21 c'/	" 114
syn match cif_symCIF_H_M	/'P -4 m 2'/	" 115
syn match cif_symCIF_H_M	/'P -4 c 2'/	" 116
syn match cif_symCIF_H_M	/'P -4 b 2'/	" 117
syn match cif_symCIF_H_M	/'P -4 n 2'/	" 118
syn match cif_symCIF_H_M	/'I -4 m 2'/	" 119
syn match cif_symCIF_H_M	/'I -4 c 2'/	" 120
syn match cif_symCIF_H_M	/'I -4 2 m'/	" 121
syn match cif_symCIF_H_M	/'I -4 2 d'/	" 122
syn match cif_symCIF_H_M	/'P 4\/m m m'/	" 123
syn match cif_symCIF_H_M	/'P 4\/m c c'/	" 124
syn match cif_symCIF_H_M	/'P 4\/n b m'/	" 125
syn match cif_symCIF_H_M	/'P 4\/n n c'/	" 126
syn match cif_symCIF_H_M	/'P 4\/m b m'/	" 127
syn match cif_symCIF_H_M	/'P 4\/m n c'/	" 128
syn match cif_symCIF_H_M	/'P 4\/n m m'/	" 129
syn match cif_symCIF_H_M	/'P 4\/n c c'/	" 130
syn match cif_symCIF_H_M	/'P 42\/m m c'/	" 131
syn match cif_symCIF_H_M	/'P 42\/m c m'/	" 132
syn match cif_symCIF_H_M	/'P 42\/n b c'/	" 133
syn match cif_symCIF_H_M	/'P 42\/n n m'/	" 134
syn match cif_symCIF_H_M	/'P 42\/m b c'/	" 135
syn match cif_symCIF_H_M	/'P 42\/m n m'/	" 136
syn match cif_symCIF_H_M	/'P 42\/n m c'/	" 137
syn match cif_symCIF_H_M	/'P 42\/n c m'/	" 138
syn match cif_symCIF_H_M	/'I 4\/m m m'/	" 139
syn match cif_symCIF_H_M	/'I 4\/m c m'/	" 140
syn match cif_symCIF_H_M	/'I 41\/a m d'/	" 141
syn match cif_symCIF_H_M	/'I 41\/a c d'/	" 142
syn match cif_symCIF_H_M	/'P 3'/		" 143
syn match cif_symCIF_H_M	/'P 31'/	" 144
syn match cif_symCIF_H_M	/'P 32'/	" 145
syn match cif_symCIF_H_M	/'R 3'/		" 146
syn match cif_symCIF_H_M	/'P -3'/	" 147
syn match cif_symCIF_H_M	/'R -3'/	" 148
syn match cif_symCIF_H_M	/'P 3 1 2'/	" 149
syn match cif_symCIF_H_M	/'P 3 2 1'/	" 150
syn match cif_symCIF_H_M	/'P 31 1 2'/	" 151
syn match cif_symCIF_H_M	/'P 31 2 1'/	" 152
syn match cif_symCIF_H_M	/'P 32 1 2'/	" 153
syn match cif_symCIF_H_M	/'P 32 2 1'/	" 154
syn match cif_symCIF_H_M	/'R 3 2'/	" 155
syn match cif_symCIF_H_M	/'P 3 m 1'/	" 156
syn match cif_symCIF_H_M	/'P 3 1 m'/	" 157
syn match cif_symCIF_H_M	/'P 3 c 1'/	" 158
syn match cif_symCIF_H_M	/'P 3 1 c'/	" 159
syn match cif_symCIF_H_M	/'R 3 m'/	" 160
syn match cif_symCIF_H_M	/'R 3 c'/	" 161
syn match cif_symCIF_H_M	/'P -3 1 m'/	" 162
syn match cif_symCIF_H_M	/'P -3 1 c'/	" 163
syn match cif_symCIF_H_M	/'P -3 m 1'/	" 164
syn match cif_symCIF_H_M	/'P -3 c 1'/	" 165
syn match cif_symCIF_H_M	/'R -3 m'/	" 166
syn match cif_symCIF_H_M	/'R -3 c'/	" 167
syn match cif_symCIF_H_M	/'P 6'/		" 168
syn match cif_symCIF_H_M	/'P 61'/	" 169
syn match cif_symCIF_H_M	/'P 65'/	" 170
syn match cif_symCIF_H_M	/'P 62'/	" 171
syn match cif_symCIF_H_M	/'P 64'/	" 172
syn match cif_symCIF_H_M	/'P 63'/	" 173
syn match cif_symCIF_H_M	/'P -6'/	" 174
syn match cif_symCIF_H_M	/'P 6\/m '/	" 175
syn match cif_symCIF_H_M	/'P 63\/m'/	" 176
syn match cif_symCIF_H_M	/'P 6 2 2'/	" 177
syn match cif_symCIF_H_M	/'P 61 2 2'/	" 178
syn match cif_symCIF_H_M	/'P 65 2 2'/	" 179
syn match cif_symCIF_H_M	/'P 62 2 2'/	" 180
syn match cif_symCIF_H_M	/'P 64 2 2'/	" 181
syn match cif_symCIF_H_M	/'P 63 2 2'/	" 182
syn match cif_symCIF_H_M	/'P 6 m m'/	" 183
syn match cif_symCIF_H_M	/'P 6 c c'/	" 184
syn match cif_symCIF_H_M	/'P 63 c m'/	" 185
syn match cif_symCIF_H_M	/'P 63 m c'/	" 186
syn match cif_symCIF_H_M	/'P -6 m 2'/	" 187
syn match cif_symCIF_H_M	/'P -6 c 2'/	" 188
syn match cif_symCIF_H_M	/'P -6 2 m'/	" 189
syn match cif_symCIF_H_M	/'P -6 2 c'/	" 190
syn match cif_symCIF_H_M	/'P 6\/m m m'/	" 191
syn match cif_symCIF_H_M	/'P 6\/m c c'/	" 192
syn match cif_symCIF_H_M	/'P 63\/m c m'/	" 193
syn match cif_symCIF_H_M	/'P 63\/m m c'/	" 194
syn match cif_symCIF_H_M	/'P 2 3'/	" 195
syn match cif_symCIF_H_M	/'F 2 3'/	" 196
syn match cif_symCIF_H_M	/'I 2 3'/	" 197
syn match cif_symCIF_H_M	/'P 21 3'/	" 198
syn match cif_symCIF_H_M	/'I 21 3'/	" 199
syn match cif_symCIF_H_M	/'P m -3'/	" 200
syn match cif_symCIF_H_M	/'P n -3'/	" 201
syn match cif_symCIF_H_M	/'F m -3'/	" 202
syn match cif_symCIF_H_M	/'F d -3'/	" 203
syn match cif_symCIF_H_M	/'I m -3'/	" 204
syn match cif_symCIF_H_M	/'P a -3'/	" 205
syn match cif_symCIF_H_M	/'I a -3'/	" 206
syn match cif_symCIF_H_M	/'P 4 3 2'/	" 207
syn match cif_symCIF_H_M	/'P 42 3 2'/	" 208
syn match cif_symCIF_H_M	/'F 4 3 2'/	" 209
syn match cif_symCIF_H_M	/'F 41 3 2'/	" 210
syn match cif_symCIF_H_M	/'I 4 3 2'/	" 211
syn match cif_symCIF_H_M	/'P 43 3 2'/	" 212
syn match cif_symCIF_H_M	/'P 41 3 2'/	" 213
syn match cif_symCIF_H_M	/'I 41 3 2'/	" 214
syn match cif_symCIF_H_M	/'P -4 3 m'/	" 215
syn match cif_symCIF_H_M	/'F -4 3 m'/	" 216
syn match cif_symCIF_H_M	/'I -4 3 m'/	" 217
syn match cif_symCIF_H_M	/'P -4 3 n'/	" 218
syn match cif_symCIF_H_M	/'F -4 3 c'/	" 219
syn match cif_symCIF_H_M	/'I -4 3 d'/	" 220
syn match cif_symCIF_H_M	/'P m -3 m'/	" 221
syn match cif_symCIF_H_M	/'P n -3 n'/	" 222
syn match cif_symCIF_H_M	/'P m -3 n'/	" 223
syn match cif_symCIF_H_M	/'P n -3 m'/	" 224
syn match cif_symCIF_H_M	/'F m -3 m'/	" 225
syn match cif_symCIF_H_M	/'F m -3 c'/	" 226
syn match cif_symCIF_H_M	/'F d -3 m'/	" 227
syn match cif_symCIF_H_M	/'F d -3 c'/	" 228
syn match cif_symCIF_H_M	/'I m -3 m'/	" 229
syn match cif_symCIF_H_M	/'I a -3 d'/	" 230

" _space_group.reference_setting {{{2
syn match cif_symCIF_Hall	/'P 1'/			" 1
syn match cif_symCIF_Hall	/'-P 1'/		" 2
syn match cif_symCIF_Hall	/'P 2y'/		" 3
syn match cif_symCIF_Hall	/'P 2yb'/		" 4
syn match cif_symCIF_Hall	/'C 2y'/		" 5
syn match cif_symCIF_Hall	/'P -2y'/		" 6
syn match cif_symCIF_Hall	/'P -2yc'/		" 7
syn match cif_symCIF_Hall	/'C -2y'/		" 8
syn match cif_symCIF_Hall	/'C -2yc'/		" 9
syn match cif_symCIF_Hall	/'-P 2y'/		" 10
syn match cif_symCIF_Hall	/'-P 2yb'/		" 11
syn match cif_symCIF_Hall	/'-C 2y'/		" 12
syn match cif_symCIF_Hall	/'-P 2yc'/		" 13
syn match cif_symCIF_Hall	/'-P 2ybc'/		" 14
syn match cif_symCIF_Hall	/'-C 2yc'/		" 15
syn match cif_symCIF_Hall	/'P 2 2'/		" 16
syn match cif_symCIF_Hall	/'P 2c 2'/		" 17
syn match cif_symCIF_Hall	/'P 2 2ab'/		" 18
syn match cif_symCIF_Hall	/'P 2ac 2ab'/		" 19
syn match cif_symCIF_Hall	/'C 2c 2'/		" 20
syn match cif_symCIF_Hall	/'C 2 2'/		" 21
syn match cif_symCIF_Hall	/'F 2 2'/		" 22
syn match cif_symCIF_Hall	/'I 2 2'/		" 23
syn match cif_symCIF_Hall	/'I 2b 2c'/		" 24
syn match cif_symCIF_Hall	/'P 2 -2'/		" 25
syn match cif_symCIF_Hall	/'P 2c -2'/		" 26
syn match cif_symCIF_Hall	/'P 2 -2c'/		" 27
syn match cif_symCIF_Hall	/'P 2 -2a'/		" 28
syn match cif_symCIF_Hall	/'P 2c -2ac'/		" 29
syn match cif_symCIF_Hall	/'P 2 -2bc'/		" 30
syn match cif_symCIF_Hall	/'P 2ac -2'/		" 31
syn match cif_symCIF_Hall	/'P 2 -2ab'/		" 32
syn match cif_symCIF_Hall	/'P 2c -2n'/		" 33
syn match cif_symCIF_Hall	/'P 2 -2n'/		" 34
syn match cif_symCIF_Hall	/'C 2 -2'/		" 35
syn match cif_symCIF_Hall	/'C 2c -2'/		" 36
syn match cif_symCIF_Hall	/'C 2 -2c'/		" 37
syn match cif_symCIF_Hall	/'A 2 -2'/		" 38
syn match cif_symCIF_Hall	/'A 2 -2b'/		" 39
syn match cif_symCIF_Hall	/'A 2 -2a'/		" 40
syn match cif_symCIF_Hall	/'A 2 -2ab'/		" 41
syn match cif_symCIF_Hall	/'F 2 -2'/		" 42
syn match cif_symCIF_Hall	/'F 2 -2d'/		" 43
syn match cif_symCIF_Hall	/'I 2 -2'/		" 44
syn match cif_symCIF_Hall	/'I 2 -2c'/		" 45
syn match cif_symCIF_Hall	/'I 2 -2a'/		" 46
syn match cif_symCIF_Hall	/'-P 2 2'/		" 47
syn match cif_symCIF_Hall	/'-P 2ab 2bc'/		" 48
syn match cif_symCIF_Hall	/'-P 2 2c'/		" 49
syn match cif_symCIF_Hall	/'-P 2ab 2b'/		" 50
syn match cif_symCIF_Hall	/'-P 2a 2a'/		" 51
syn match cif_symCIF_Hall	/'-P 2a 2bc'/		" 52
syn match cif_symCIF_Hall	/'-P 2ac 2'/		" 53
syn match cif_symCIF_Hall	/'-P 2a 2ac'/		" 54
syn match cif_symCIF_Hall	/'-P 2 2ab'/		" 55
syn match cif_symCIF_Hall	/'-P 2ab 2ac'/		" 56
syn match cif_symCIF_Hall	/'-P 2c 2b'/		" 57
syn match cif_symCIF_Hall	/'-P 2 2n'/		" 58
syn match cif_symCIF_Hall	/'-P 2ab 2a'/		" 59
syn match cif_symCIF_Hall	/'-P 2n 2ab'/		" 60
syn match cif_symCIF_Hall	/'-P 2ac 2ab'/		" 61
syn match cif_symCIF_Hall	/'-P 2ac 2n'/		" 62
syn match cif_symCIF_Hall	/'-C 2c 2'/		" 63
syn match cif_symCIF_Hall	/'-C 2ac 2'/		" 64
syn match cif_symCIF_Hall	/'-C 2 2'/		" 65
syn match cif_symCIF_Hall	/'-C 2 2c'/		" 66
syn match cif_symCIF_Hall	/'-C 2a 2'/		" 67
syn match cif_symCIF_Hall	/'-C 2a 2ac'/		" 68
syn match cif_symCIF_Hall	/'-F 2 2'/		" 69
syn match cif_symCIF_Hall	/'-F 2uv 2vw'/		" 70
syn match cif_symCIF_Hall	/'-I 2 2'/		" 71
syn match cif_symCIF_Hall	/'-I 2 2c'/		" 72
syn match cif_symCIF_Hall	/'-I 2b 2c'/		" 73
syn match cif_symCIF_Hall	/'-I 2b 2'/		" 74
syn match cif_symCIF_Hall	/'P 4'/			" 75
syn match cif_symCIF_Hall	/'P 4w'/		" 76
syn match cif_symCIF_Hall	/'P 4c'/		" 77
syn match cif_symCIF_Hall	/'P 4cw'/		" 78
syn match cif_symCIF_Hall	/'I 4'/			" 79
syn match cif_symCIF_Hall	/'I 4bw'/		" 80
syn match cif_symCIF_Hall	/'P -4'/		" 81
syn match cif_symCIF_Hall	/'I -4'/		" 82
syn match cif_symCIF_Hall	/'-P 4'/		" 83
syn match cif_symCIF_Hall	/'-P 4c'/		" 84
syn match cif_symCIF_Hall	/'-P 4a'/		" 85
syn match cif_symCIF_Hall	/'-P 4bc'/		" 86
syn match cif_symCIF_Hall	/'-I 4'/		" 87
syn match cif_symCIF_Hall	/'-I 4ad'/		" 88
syn match cif_symCIF_Hall	/'P 4 2'/		" 89
syn match cif_symCIF_Hall	/'P 4ab 2ab'/		" 90
syn match cif_symCIF_Hall	/'P 4w 2c'/		" 91
syn match cif_symCIF_Hall	/'P 4abw 2nw'/		" 92
syn match cif_symCIF_Hall	/'P 4c 2'/		" 93
syn match cif_symCIF_Hall	/'P 4n 2n'/		" 94
syn match cif_symCIF_Hall	/'P 4cw 2c'/		" 95
syn match cif_symCIF_Hall	/'P 4nw 2abw'/		" 96
syn match cif_symCIF_Hall	/'I 4 2'/		" 97
syn match cif_symCIF_Hall	/'I 4bw 2bw'/		" 98
syn match cif_symCIF_Hall	/'P 4 -2'/		" 99
syn match cif_symCIF_Hall	/'P 4 -2ab'/		" 100
syn match cif_symCIF_Hall	/'P 4c -2c'/		" 101
syn match cif_symCIF_Hall	/'P 4n -2n'/		" 102
syn match cif_symCIF_Hall	/'P 4 -2c'/		" 103
syn match cif_symCIF_Hall	/'P 4 -2n'/		" 104
syn match cif_symCIF_Hall	/'P 4c -2'/		" 105
syn match cif_symCIF_Hall	/'P 4c -2ab'/		" 106
syn match cif_symCIF_Hall	/'I 4 -2'/		" 107
syn match cif_symCIF_Hall	/'I 4 -2c'/		" 108
syn match cif_symCIF_Hall	/'I 4bw -2'/		" 109
syn match cif_symCIF_Hall	/'I 4bw -2c'/		" 110
syn match cif_symCIF_Hall	/'P -4 2'/		" 111
syn match cif_symCIF_Hall	/'P -4 2c'/		" 112
syn match cif_symCIF_Hall	/'P -4 2ab'/		" 113
syn match cif_symCIF_Hall	/'P -4 2n'/		" 114
syn match cif_symCIF_Hall	/'P -4 -2'/		" 115
syn match cif_symCIF_Hall	/'P -4 -2c'/		" 116
syn match cif_symCIF_Hall	/'P -4 -2ab'/		" 117
syn match cif_symCIF_Hall	/'P -4 -2n'/		" 118
syn match cif_symCIF_Hall	/'I -4 -2'/		" 119
syn match cif_symCIF_Hall	/'I -4 -2c'/		" 120
syn match cif_symCIF_Hall	/'I -4 2'/		" 121
syn match cif_symCIF_Hall	/'I -4 2bw'/		" 122
syn match cif_symCIF_Hall	/'-P 4 2'/		" 123
syn match cif_symCIF_Hall	/'-P 4 2c'/		" 124
syn match cif_symCIF_Hall	/'-P 4a 2b'/		" 125
syn match cif_symCIF_Hall	/'-P 4a 2bc'/		" 126
syn match cif_symCIF_Hall	/'-P 4 2ab'/		" 127
syn match cif_symCIF_Hall	/'-P 4 2n'/		" 128
syn match cif_symCIF_Hall	/'-P 4a 2a'/		" 129
syn match cif_symCIF_Hall	/'-P 4a 2ac'/		" 130
syn match cif_symCIF_Hall	/'-P 4c 2'/		" 131
syn match cif_symCIF_Hall	/'-P 4c 2c'/		" 132
syn match cif_symCIF_Hall	/'-P 4ac 2b'/		" 133
syn match cif_symCIF_Hall	/'-P 4ac 2bc'/		" 134
syn match cif_symCIF_Hall	/'-P 4c 2ab'/		" 135
syn match cif_symCIF_Hall	/'-P 4n 2n'/		" 136
syn match cif_symCIF_Hall	/'-P 4ac 2a'/		" 137
syn match cif_symCIF_Hall	/'-P 4ac 2ac'/		" 138
syn match cif_symCIF_Hall	/'-I 4 2'/		" 139
syn match cif_symCIF_Hall	/'-I 4 2c'/		" 140
syn match cif_symCIF_Hall	/'-I 4bd 2'/		" 141
syn match cif_symCIF_Hall	/'-I 4bd 2c'/		" 142
syn match cif_symCIF_Hall	/'P 3'/			" 143
syn match cif_symCIF_Hall	/'P 31'/		" 144
syn match cif_symCIF_Hall	/'P 32'/		" 145
syn match cif_symCIF_Hall	/'R 3'/			" 146
syn match cif_symCIF_Hall	/'-P 3'/		" 147
syn match cif_symCIF_Hall	/'-R 3'/		" 148
syn match cif_symCIF_Hall	/'P 3 2'/		" 149
syn match cif_symCIF_Hall	/'P 3 2"'/		" 150
syn match cif_symCIF_Hall	/'P 31 2 (0 0 4)'/	" 151
syn match cif_symCIF_Hall	/'P 31 2"'/		" 152
syn match cif_symCIF_Hall	/'P 32 2 (0 0 2)'/	" 153
syn match cif_symCIF_Hall	/'P 32 2"'/		" 154
syn match cif_symCIF_Hall	/'R 3 2"'/		" 155
syn match cif_symCIF_Hall	/'P 3 -2"'/		" 156
syn match cif_symCIF_Hall	/'P 3 -2'/		" 157
syn match cif_symCIF_Hall	/'P 3 -2"c'/		" 158
syn match cif_symCIF_Hall	/'P 3 -2c'/		" 159
syn match cif_symCIF_Hall	/'R 3 -2"'/		" 160
syn match cif_symCIF_Hall	/'R 3 -2"c'/		" 161
syn match cif_symCIF_Hall	/'-P 3 2'/		" 162
syn match cif_symCIF_Hall	/'-P 3 2c'/		" 163
syn match cif_symCIF_Hall	/'-P 3 2"'/		" 164
syn match cif_symCIF_Hall	/'-P 3 2"c'/		" 165
syn match cif_symCIF_Hall	/'-R 3 2"'/		" 166
syn match cif_symCIF_Hall	/'-R 3 2"c'/		" 167
syn match cif_symCIF_Hall	/'P 6'/			" 168
syn match cif_symCIF_Hall	/'P 61'/		" 169
syn match cif_symCIF_Hall	/'P 65'/		" 170
syn match cif_symCIF_Hall	/'P 62'/		" 171
syn match cif_symCIF_Hall	/'P 64'/		" 172
syn match cif_symCIF_Hall	/'P 6c'/		" 173
syn match cif_symCIF_Hall	/'P -6'/		" 174
syn match cif_symCIF_Hall	/'-P 6'/		" 175
syn match cif_symCIF_Hall	/'-P 6c'/		" 176
syn match cif_symCIF_Hall	/'P 6 2'/		" 177
syn match cif_symCIF_Hall	/'P 61 2 (0 0 5)'/	" 178
syn match cif_symCIF_Hall	/'P 65 2 (0 0 1)'/	" 179
syn match cif_symCIF_Hall	/'P 62 2 (0 0 4)'/	" 180
syn match cif_symCIF_Hall	/'P 64 2 (0 0 2)'/	" 181
syn match cif_symCIF_Hall	/'P 6c 2c'/		" 182
syn match cif_symCIF_Hall	/'P 6 -2'/		" 183
syn match cif_symCIF_Hall	/'P 6 -2c'/		" 184
syn match cif_symCIF_Hall	/'P 6c -2'/		" 185
syn match cif_symCIF_Hall	/'P 6c -2c'/		" 186
syn match cif_symCIF_Hall	/'P -6 2'/		" 187
syn match cif_symCIF_Hall	/'P -6c 2'/		" 188
syn match cif_symCIF_Hall	/'P -6 -2'/		" 189
syn match cif_symCIF_Hall	/'P -6c -2c'/		" 190
syn match cif_symCIF_Hall	/'-P 6 2'/		" 191
syn match cif_symCIF_Hall	/'-P 6 2c'/		" 192
syn match cif_symCIF_Hall	/'-P 6c 2'/		" 193
syn match cif_symCIF_Hall	/'-P 6c 2c'/		" 194
syn match cif_symCIF_Hall	/'P 2 2 3'/		" 195
syn match cif_symCIF_Hall	/'F 2 2 3'/		" 196
syn match cif_symCIF_Hall	/'I 2 2 3'/		" 197
syn match cif_symCIF_Hall	/'P 2ac 2ab 3'/		" 198
syn match cif_symCIF_Hall	/'I 2b 2c 3'/		" 199
syn match cif_symCIF_Hall	/'-P 2 2 3'/		" 200
syn match cif_symCIF_Hall	/'-P 2ab 2bc 3'/	" 201
syn match cif_symCIF_Hall	/'-F 2 2 3'/		" 202
syn match cif_symCIF_Hall	/'-F 2uv 2vw 3'/	" 203
syn match cif_symCIF_Hall	/'-I 2 2 3'/		" 204
syn match cif_symCIF_Hall	/'-P 2ac 2ab 3'/	" 205
syn match cif_symCIF_Hall	/'-I 2b 2c 3'/		" 206
syn match cif_symCIF_Hall	/'P 4 2 3'/		" 207
syn match cif_symCIF_Hall	/'P 4n 2 3'/		" 208
syn match cif_symCIF_Hall	/'F 4 2 3'/		" 209
syn match cif_symCIF_Hall	/'F 4d 2 3'/		" 210
syn match cif_symCIF_Hall	/'I 4 2 3'/		" 211
syn match cif_symCIF_Hall	/'P 4acd 2ab 3'/	" 212
syn match cif_symCIF_Hall	/'P 4bd 2ab 3'/		" 213
syn match cif_symCIF_Hall	/'I 4bd 2c 3'/		" 214
syn match cif_symCIF_Hall	/'P -4 2 3'/		" 215
syn match cif_symCIF_Hall	/'F -4 2 3'/		" 216
syn match cif_symCIF_Hall	/'I -4 2 3'/		" 217
syn match cif_symCIF_Hall	/'P -4n 2 3'/		" 218
syn match cif_symCIF_Hall	/'F -4a 2 3'/		" 219
syn match cif_symCIF_Hall	/'I -4bd 2c 3'/		" 220
syn match cif_symCIF_Hall	/'-P 4 2 3'/		" 221
syn match cif_symCIF_Hall	/'-P 4a 2bc 3'/		" 222
syn match cif_symCIF_Hall	/'-P 4n 2 3'/		" 223
syn match cif_symCIF_Hall	/'-P 4bc 2bc 3'/	" 224
syn match cif_symCIF_Hall	/'-F 4 2 3'/		" 225
syn match cif_symCIF_Hall	/'-F 4a 2 3'/		" 226
syn match cif_symCIF_Hall	/'-F 4vw 2vw 3'/	" 227
syn match cif_symCIF_Hall	/'-F 4ud 2vw 3'/	" 228
syn match cif_symCIF_Hall	/'-I 4 2 3'/		" 229
syn match cif_symCIF_Hall	/'-I 4bd 2c 3'/		" 230
" }}}1

hi def link cifBlock	Identifier
hi def link cifComment	Comment
hi def link cifSpecial	Special
hi def link cifString	String

hi def link cif_coreCIF	Identifier
hi def link cif_coreCIFDeprecated	Error

hi def link cif_symCIF_Hall	Special
hi def link cif_symCIF_H_M	Special

let b:current_syntax = 'cif'
let &cpo = s:cpo_save
unlet s:cpo_save
